import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Helper to calculate tier from IQ score
function getTier(iqScore: number): 'DIAMOND' | 'PLATINUM' | 'GOLD' | 'SILVER' | 'BRONZE' {
  if (iqScore >= 95) return 'DIAMOND';
  if (iqScore >= 90) return 'PLATINUM';
  if (iqScore >= 85) return 'GOLD';
  if (iqScore >= 75) return 'SILVER';
  return 'BRONZE';
}

// 30+ real US craft breweries with accurate data
const breweries = [
  {
    name: 'Sierra Nevada Brewing Co.',
    slug: 'sierra-nevada',
    type: 'REGIONAL' as const,
    description: 'Founded by Ken Grossman in 1980, Sierra Nevada helped launch the American craft beer revolution. Their Pale Ale remains one of the most iconic beers in craft brewing history.',
    city: 'Chico',
    state: 'CA',
    country: 'USA',
    latitude: 39.7241,
    longitude: -121.8147,
    specialties: ['Pale Ale', 'IPA', 'Seasonal Ales'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1980,
    iqScore: 92,
    isVerified: true,
  },
  {
    name: 'Dogfish Head Craft Brewery',
    slug: 'dogfish-head',
    type: 'REGIONAL' as const,
    description: 'Sam Calagione founded Dogfish Head in 1995 with a mission to brew off-centered ales for off-centered people. Known for innovative ingredients and continuous hopping techniques.',
    city: 'Milton',
    state: 'DE',
    country: 'USA',
    latitude: 38.7776,
    longitude: -75.3099,
    specialties: ['IPA', 'Experimental Ales', 'Session Sours'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 1995,
    iqScore: 89,
    isVerified: true,
  },
  {
    name: "Bell's Brewery",
    slug: 'bells',
    type: 'REGIONAL' as const,
    description: "Larry Bell started brewing in a 15-gallon soup kettle in 1985 in Kalamazoo, Michigan. Bell's has grown into one of the largest independent craft breweries in the US, beloved for Two Hearted Ale and Oberon.",
    city: 'Comstock',
    state: 'MI',
    country: 'USA',
    latitude: 42.2859,
    longitude: -85.5134,
    specialties: ['IPA', 'Wheat Ale', 'Stout'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1985,
    iqScore: 93,
    isVerified: true,
  },
  {
    name: 'Founders Brewing Co.',
    slug: 'founders',
    type: 'REGIONAL' as const,
    description: 'Founded in 1997 in Grand Rapids, Michigan. Founders earned a national reputation with bold beers like KBS and Breakfast Stout. Their All Day IPA became one of the top-selling craft beers in America.',
    city: 'Grand Rapids',
    state: 'MI',
    country: 'USA',
    latitude: 42.9580,
    longitude: -85.6742,
    specialties: ['Stout', 'IPA', 'Barrel-Aged'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 1997,
    iqScore: 91,
    isVerified: true,
  },
  {
    name: 'Stone Brewing',
    slug: 'stone',
    type: 'REGIONAL' as const,
    description: 'Greg Koch and Steve Wagner founded Stone in 1996 in San Diego. Known for aggressively hoppy beers and bold branding, Stone helped define the West Coast IPA style.',
    city: 'Escondido',
    state: 'CA',
    country: 'USA',
    latitude: 33.1159,
    longitude: -117.1206,
    specialties: ['IPA', 'Pale Ale', 'Strong Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1996,
    iqScore: 85,
    isVerified: true,
  },
  {
    name: 'Deschutes Brewery',
    slug: 'deschutes',
    type: 'REGIONAL' as const,
    description: 'Founded in 1988 in Bend, Oregon, Deschutes started as a small brewpub and grew into one of the premier craft breweries in the Pacific Northwest. Known for balanced, flavorful beers.',
    city: 'Bend',
    state: 'OR',
    country: 'USA',
    latitude: 44.0582,
    longitude: -121.3153,
    specialties: ['IPA', 'Porter', 'Pale Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1988,
    iqScore: 88,
    isVerified: true,
  },
  {
    name: 'Lagunitas Brewing Company',
    slug: 'lagunitas',
    type: 'REGIONAL' as const,
    description: 'Tony Magee founded Lagunitas in 1993 in Petaluma, California. Famous for their IPA and irreverent attitude, Lagunitas became one of the fastest-growing craft breweries in the country.',
    city: 'Petaluma',
    state: 'CA',
    country: 'USA',
    latitude: 38.2366,
    longitude: -122.6380,
    specialties: ['IPA', 'Pale Ale', 'Strong Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1993,
    iqScore: 84,
    isVerified: true,
  },
  {
    name: 'New Belgium Brewing Company',
    slug: 'new-belgium',
    type: 'REGIONAL' as const,
    description: 'Founded in 1991 in Fort Collins, Colorado, New Belgium is known for Fat Tire and Voodoo Ranger. They were a pioneer in employee-owned craft brewing and environmental sustainability.',
    city: 'Fort Collins',
    state: 'CO',
    country: 'USA',
    latitude: 40.5939,
    longitude: -105.0681,
    specialties: ['Amber Ale', 'IPA', 'Sour'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1991,
    iqScore: 82,
    isVerified: true,
  },
  {
    name: 'Firestone Walker Brewing Company',
    slug: 'firestone-walker',
    type: 'REGIONAL' as const,
    description: 'Founded in 1996 in Paso Robles, California. Firestone Walker is renowned for their barrel-aged beers and the annual Parabola release. Their Union Jack IPA helped popularize the West Coast style.',
    city: 'Paso Robles',
    state: 'CA',
    country: 'USA',
    latitude: 35.6369,
    longitude: -120.6545,
    specialties: ['Barrel-Aged', 'IPA', 'Pale Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1996,
    iqScore: 93,
    isVerified: true,
  },
  {
    name: 'Russian River Brewing Company',
    slug: 'russian-river',
    type: 'BREWPUB' as const,
    description: 'Vinnie Cilurzo founded Russian River in 1997 in Santa Rosa, California. Home of Pliny the Elder and Pliny the Younger, widely considered among the finest IPAs ever brewed.',
    city: 'Santa Rosa',
    state: 'CA',
    country: 'USA',
    latitude: 38.4405,
    longitude: -122.7141,
    specialties: ['Double IPA', 'Sour', 'Belgian-Style'],
    hasTaproom: true,
    hasTours: false,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 1997,
    iqScore: 95,
    isVerified: true,
  },
  {
    name: 'Tree House Brewing Company',
    slug: 'tree-house',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2011 in Charlton, Massachusetts. Tree House rocketed to fame with their New England-style IPAs, particularly Julius. Known for on-site-only sales and passionate fan following.',
    city: 'Charlton',
    state: 'MA',
    country: 'USA',
    latitude: 42.1251,
    longitude: -71.9837,
    specialties: ['NEIPA', 'Stout', 'Pale Ale'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2011,
    iqScore: 95,
    isVerified: true,
  },
  {
    name: 'The Alchemist',
    slug: 'alchemist',
    type: 'MICROBREWERY' as const,
    description: 'John Kimmich founded The Alchemist in 2003 in Stowe, Vermont. Heady Topper is widely credited as the beer that launched the hazy IPA revolution and remains one of the most sought-after beers in America.',
    city: 'Stowe',
    state: 'VT',
    country: 'USA',
    latitude: 44.4654,
    longitude: -72.6874,
    specialties: ['Hazy IPA', 'Double IPA'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2003,
    iqScore: 94,
    isVerified: true,
  },
  {
    name: 'Other Half Brewing Co.',
    slug: 'other-half',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2014 in Brooklyn, New York. Other Half quickly became one of the most respected hazy IPA producers in the country, known for bold hop-forward beers and creative collaborations.',
    city: 'Brooklyn',
    state: 'NY',
    country: 'USA',
    latitude: 40.6735,
    longitude: -73.9981,
    specialties: ['NEIPA', 'Imperial Stout', 'Sour'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2014,
    iqScore: 92,
    isVerified: true,
  },
  {
    name: 'Trillium Brewing Company',
    slug: 'trillium',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2013 in Boston, Massachusetts. Trillium has earned a devoted following for their exceptional New England IPAs and wild ales, establishing themselves as a cornerstone of the New England craft beer scene.',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    latitude: 42.3474,
    longitude: -71.0560,
    specialties: ['NEIPA', 'Wild Ale', 'Farmhouse'],
    hasTaproom: true,
    hasTours: false,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 2013,
    iqScore: 93,
    isVerified: true,
  },
  {
    name: 'Modern Times Beer',
    slug: 'modern-times',
    type: 'CRAFT' as const,
    description: 'Founded in 2013 in San Diego, California. Modern Times is known for creative branding, employee ownership, and innovative beers spanning hoppy, dark, and sour styles.',
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    latitude: 32.8843,
    longitude: -117.1500,
    specialties: ['IPA', 'Stout', 'Sour'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 2013,
    iqScore: 86,
    isVerified: true,
  },
  {
    name: 'Cigar City Brewing',
    slug: 'cigar-city',
    type: 'REGIONAL' as const,
    description: 'Joey Redner founded Cigar City in 2009 in Tampa, Florida. Their flagship Jai Alai IPA became one of the most popular craft beers in the Southeast, and Hunahpu Imperial Stout draws thousands annually.',
    city: 'Tampa',
    state: 'FL',
    country: 'USA',
    latitude: 27.9599,
    longitude: -82.5062,
    specialties: ['IPA', 'Imperial Stout', 'Lager'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 2009,
    iqScore: 89,
    isVerified: true,
  },
  {
    name: 'Prairie Artisan Ales',
    slug: 'prairie-artisan',
    type: 'CRAFT' as const,
    description: 'Founded in 2012 in Oklahoma City, Oklahoma. Prairie Artisan Ales quickly gained recognition for their farmhouse ales and bold imperial stouts, bringing world-class craft beer to the heartland.',
    city: 'Oklahoma City',
    state: 'OK',
    country: 'USA',
    latitude: 35.4676,
    longitude: -97.5164,
    specialties: ['Farmhouse Ale', 'Imperial Stout', 'Sour'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2012,
    iqScore: 85,
    isVerified: true,
  },
  {
    name: 'Toppling Goliath Brewing Co.',
    slug: 'toppling-goliath',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2009 in Decorah, Iowa. Despite its small-town location, Toppling Goliath has earned a national reputation for world-class IPAs including King Sue and PseudoSue.',
    city: 'Decorah',
    state: 'IA',
    country: 'USA',
    latitude: 43.3016,
    longitude: -91.7877,
    specialties: ['IPA', 'DIPA', 'Stout'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2009,
    iqScore: 93,
    isVerified: true,
  },
  {
    name: '3 Floyds Brewing Co.',
    slug: '3-floyds',
    type: 'BREWPUB' as const,
    description: 'Founded in 1996 in Munster, Indiana. 3 Floyds is legendary for Dark Lord Day and aggressive, hop-forward beers like Zombie Dust. Their cult following extends far beyond the Midwest.',
    city: 'Munster',
    state: 'IN',
    country: 'USA',
    latitude: 41.5645,
    longitude: -87.5126,
    specialties: ['Pale Ale', 'Imperial Stout', 'IPA'],
    hasTaproom: true,
    hasTours: false,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 1996,
    iqScore: 91,
    isVerified: true,
  },
  {
    name: 'Half Acre Beer Company',
    slug: 'half-acre',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2006 in Chicago, Illinois. Half Acre has become a beloved neighborhood brewery known for their approachable yet creative beers and vibrant taproom culture.',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    latitude: 41.9676,
    longitude: -87.6831,
    specialties: ['IPA', 'Lager', 'Pale Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 2006,
    iqScore: 86,
    isVerified: true,
  },
  {
    name: 'Surly Brewing Company',
    slug: 'surly',
    type: 'REGIONAL' as const,
    description: 'Omar Ansari founded Surly in 2006 in Minneapolis, Minnesota. Surly changed Minnesota beer laws to allow taprooms and produces bold, unapologetic beers including Furious and Darkness.',
    city: 'Minneapolis',
    state: 'MN',
    country: 'USA',
    latitude: 44.9733,
    longitude: -93.2105,
    specialties: ['IPA', 'Imperial Stout', 'Pale Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 2006,
    iqScore: 88,
    isVerified: true,
  },
  {
    name: 'Odell Brewing Company',
    slug: 'odell',
    type: 'REGIONAL' as const,
    description: 'Founded in 1989 in Fort Collins, Colorado. Odell is one of the longest-running independent craft breweries in the Rockies, known for balanced, sessionable beers and strong community ties.',
    city: 'Fort Collins',
    state: 'CO',
    country: 'USA',
    latitude: 40.5894,
    longitude: -105.0632,
    specialties: ['IPA', 'Pale Ale', 'Pilsner'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1989,
    iqScore: 84,
    isVerified: true,
  },
  {
    name: 'Great Notion Brewing',
    slug: 'great-notion',
    type: 'BREWPUB' as const,
    description: 'Founded in 2016 in Portland, Oregon. Great Notion quickly became one of the most creative breweries in the Pacific Northwest, known for fruit-forward sours, hazy IPAs, and pastry stouts.',
    city: 'Portland',
    state: 'OR',
    country: 'USA',
    latitude: 45.5578,
    longitude: -122.6500,
    specialties: ['Sour', 'NEIPA', 'Pastry Stout'],
    hasTaproom: true,
    hasTours: false,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 2016,
    iqScore: 90,
    isVerified: true,
  },
  {
    name: 'Wicked Weed Brewing',
    slug: 'wicked-weed',
    type: 'BREWPUB' as const,
    description: 'Founded in 2012 in Asheville, North Carolina. Wicked Weed made a name with their exceptional sour and wild ale program at their Funkatorium, alongside strong hop-forward offerings.',
    city: 'Asheville',
    state: 'NC',
    country: 'USA',
    latitude: 35.5943,
    longitude: -82.5512,
    specialties: ['Sour', 'Wild Ale', 'IPA'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 2012,
    iqScore: 85,
    isVerified: true,
  },
  {
    name: 'Boulevard Brewing Company',
    slug: 'boulevard',
    type: 'REGIONAL' as const,
    description: 'Founded in 1989 in Kansas City, Missouri. Boulevard is the largest specialty brewer in the Midwest, known for their Unfiltered Wheat and Tank 7 Farmhouse Ale.',
    city: 'Kansas City',
    state: 'MO',
    country: 'USA',
    latitude: 39.0836,
    longitude: -94.5986,
    specialties: ['Wheat Ale', 'Farmhouse Ale', 'IPA'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 1989,
    iqScore: 84,
    isVerified: true,
  },
  {
    name: 'Left Hand Brewing Company',
    slug: 'left-hand',
    type: 'REGIONAL' as const,
    description: 'Founded in 1993 in Longmont, Colorado. Left Hand pioneered the nitro bottle with their Milk Stout Nitro and has been a staple of the Colorado craft beer scene for three decades.',
    city: 'Longmont',
    state: 'CO',
    country: 'USA',
    latitude: 40.1672,
    longitude: -105.1019,
    specialties: ['Stout', 'Nitro', 'Porter'],
    hasTaproom: true,
    hasTours: true,
    hasFood: false,
    dogFriendly: true,
    foundedYear: 1993,
    iqScore: 82,
    isVerified: true,
  },
  {
    name: 'Oskar Blues Brewery',
    slug: 'oskar-blues',
    type: 'REGIONAL' as const,
    description: 'Founded in 1997 in Brevard, North Carolina. Oskar Blues was the first craft brewery to can their beer with Dale\'s Pale Ale in 2002, helping to launch the craft canning revolution.',
    city: 'Brevard',
    state: 'NC',
    country: 'USA',
    latitude: 35.2334,
    longitude: -82.7312,
    specialties: ['Pale Ale', 'IPA', 'Pilsner'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 1997,
    iqScore: 83,
    isVerified: true,
  },
  {
    name: 'AleSmith Brewing Company',
    slug: 'alesmith',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 1995 in San Diego, California. AleSmith is known for meticulous attention to detail and their Speedway Stout, one of the most awarded imperial stouts in America.',
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    latitude: 32.8484,
    longitude: -117.1286,
    specialties: ['Imperial Stout', 'IPA', 'Strong Ale'],
    hasTaproom: true,
    hasTours: true,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 1995,
    iqScore: 90,
    isVerified: true,
  },
  {
    name: 'Revolution Brewing',
    slug: 'revolution',
    type: 'BREWPUB' as const,
    description: 'Founded in 2010 in Chicago, Illinois. Revolution has grown into the largest independently owned brewery in Illinois, known for Anti-Hero IPA and their impressive Deep Wood barrel-aged series.',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    latitude: 41.9219,
    longitude: -87.6980,
    specialties: ['IPA', 'Barrel-Aged', 'Lager'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: false,
    foundedYear: 2010,
    iqScore: 87,
    isVerified: true,
  },
  {
    name: 'Montauk Brewing Company',
    slug: 'montauk',
    type: 'CRAFT' as const,
    description: 'Founded in 2012 in Montauk, New York. Born from the laid-back surf culture of Long Island\'s east end, Montauk Brewing produces approachable, sessionable beers that pair perfectly with the beach lifestyle.',
    city: 'Montauk',
    state: 'NY',
    country: 'USA',
    latitude: 41.0357,
    longitude: -71.9548,
    specialties: ['IPA', 'Session Ale', 'Pilsner'],
    hasTaproom: true,
    hasTours: true,
    hasFood: false,
    dogFriendly: true,
    foundedYear: 2012,
    iqScore: 78,
    isVerified: true,
  },
  {
    name: 'Hill Farmstead Brewery',
    slug: 'hill-farmstead',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2010 by Shaun Hill in Greensboro, Vermont. Repeatedly named the best brewery in the world, Hill Farmstead produces transcendent farmhouse ales, IPAs, and stouts from a remote hilltop farm.',
    city: 'Greensboro',
    state: 'VT',
    country: 'USA',
    latitude: 44.5953,
    longitude: -72.2943,
    specialties: ['Farmhouse Ale', 'IPA', 'Pale Ale'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2010,
    iqScore: 97,
    isVerified: true,
  },
  {
    name: 'Maine Beer Company',
    slug: 'maine-beer',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2009 in Freeport, Maine. With their "Do What\'s Right" motto, Maine Beer Company produces some of the cleanest, most balanced hop-forward beers in the country, led by Lunch and Dinner.',
    city: 'Freeport',
    state: 'ME',
    country: 'USA',
    latitude: 43.8562,
    longitude: -70.1031,
    specialties: ['IPA', 'Pale Ale', 'DIPA'],
    hasTaproom: true,
    hasTours: false,
    hasFood: false,
    dogFriendly: false,
    foundedYear: 2009,
    iqScore: 92,
    isVerified: true,
  },
  {
    name: 'Jester King Brewery',
    slug: 'jester-king',
    type: 'MICROBREWERY' as const,
    description: 'Founded in 2010 in Austin, Texas. Jester King is a farmhouse brewery specializing in wild and spontaneously fermented ales, capturing the terroir of the Texas Hill Country in every bottle.',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    latitude: 30.2267,
    longitude: -98.1384,
    specialties: ['Wild Ale', 'Farmhouse Ale', 'Spontaneous Fermentation'],
    hasTaproom: true,
    hasTours: true,
    hasFood: true,
    dogFriendly: true,
    foundedYear: 2010,
    iqScore: 92,
    isVerified: true,
  },
];

// 100+ real beers across the breweries (3-5 per brewery)
const beers: {
  name: string;
  slug: string;
  brewerySlug: string;
  style: string;
  description: string;
  abv: number;
  ibu: number;
  iqScore: number;
  flavorTags: string[];
  foodPairings: string[];
  availability: string;
}[] = [
  // Sierra Nevada (5 beers)
  {
    name: 'Sierra Nevada Pale Ale',
    slug: 'sierra-nevada-pale-ale',
    brewerySlug: 'sierra-nevada',
    style: 'Pale Ale',
    description: 'The iconic American pale ale that helped launch the craft beer revolution. Cascade hops deliver bright citrus and pine.',
    abv: 5.6,
    ibu: 38,
    iqScore: 88,
    flavorTags: ['Citrus', 'Pine', 'Crisp', 'Balanced', 'Floral'],
    foodPairings: ['Grilled chicken', 'Fish tacos', 'Sharp cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Sierra Nevada Torpedo Extra IPA',
    slug: 'sierra-nevada-torpedo',
    brewerySlug: 'sierra-nevada',
    style: 'IPA',
    description: 'Dry-hopped using the innovative Hop Torpedo device for intense hop flavor. Bold and resinous with a clean malt backbone.',
    abv: 7.2,
    ibu: 65,
    iqScore: 83,
    flavorTags: ['Resinous', 'Citrus', 'Pine', 'Bold'],
    foodPairings: ['Spicy Thai', 'Pepper jack cheese', 'BBQ ribs'],
    availability: 'Year-round',
  },
  {
    name: 'Hazy Little Thing',
    slug: 'sierra-nevada-hazy-little-thing',
    brewerySlug: 'sierra-nevada',
    style: 'Hazy IPA',
    description: 'An unfiltered, unprocessed IPA bursting with tropical hop character. Juicy, smooth, and extremely drinkable.',
    abv: 6.7,
    ibu: 35,
    iqScore: 82,
    flavorTags: ['Tropical', 'Juicy', 'Smooth', 'Hazy'],
    foodPairings: ['Fish and chips', 'Guacamole', 'Tacos'],
    availability: 'Year-round',
  },
  {
    name: 'Celebration Ale',
    slug: 'sierra-nevada-celebration',
    brewerySlug: 'sierra-nevada',
    style: 'IPA',
    description: 'An annual holiday tradition since 1981. Fresh whole-cone Cascade and Centennial hops deliver bright, festive hop character.',
    abv: 6.8,
    ibu: 65,
    iqScore: 89,
    flavorTags: ['Pine', 'Citrus', 'Floral', 'Complex'],
    foodPairings: ['Roast turkey', 'Pecan pie', 'Aged gouda'],
    availability: 'Seasonal',
  },
  {
    name: 'Sierra Nevada Bigfoot',
    slug: 'sierra-nevada-bigfoot',
    brewerySlug: 'sierra-nevada',
    style: 'Barleywine',
    description: 'A legendary American barleywine with massive hop character and rich malt complexity. Ages beautifully for years.',
    abv: 9.6,
    ibu: 90,
    iqScore: 90,
    flavorTags: ['Caramel', 'Pine', 'Complex', 'Bitter', 'Warming'],
    foodPairings: ['Blue cheese', 'Dark chocolate', 'Braised short ribs'],
    availability: 'Seasonal',
  },

  // Dogfish Head (4 beers)
  {
    name: '60 Minute IPA',
    slug: 'dogfish-head-60-minute-ipa',
    brewerySlug: 'dogfish-head',
    style: 'IPA',
    description: 'Continuously hopped for 60 minutes with over 60 hop additions. A perfectly balanced, session-strength IPA.',
    abv: 6.0,
    ibu: 60,
    iqScore: 85,
    flavorTags: ['Citrus', 'Balanced', 'Smooth', 'Pine'],
    foodPairings: ['Grilled shrimp', 'Caesar salad', 'Gouda'],
    availability: 'Year-round',
  },
  {
    name: '90 Minute IPA',
    slug: 'dogfish-head-90-minute-ipa',
    brewerySlug: 'dogfish-head',
    style: 'Imperial IPA',
    description: 'Continuously hopped for 90 minutes with over 90 hop additions. Rich, malty, and intensely hoppy with warming alcohol.',
    abv: 9.0,
    ibu: 90,
    iqScore: 88,
    flavorTags: ['Hoppy', 'Malty', 'Warming', 'Complex', 'Citrus'],
    foodPairings: ['Aged cheddar', 'Lamb chops', 'Carrot cake'],
    availability: 'Year-round',
  },
  {
    name: 'Slightly Mighty',
    slug: 'dogfish-head-slightly-mighty',
    brewerySlug: 'dogfish-head',
    style: 'Lo-Cal IPA',
    description: 'A full-flavored IPA with only 95 calories. Brewed with monk fruit for a dry, tropical hop character without the heaviness.',
    abv: 4.0,
    ibu: 30,
    iqScore: 76,
    flavorTags: ['Tropical', 'Light', 'Crisp', 'Sessionable'],
    foodPairings: ['Grilled fish', 'Mixed greens salad', 'Hummus'],
    availability: 'Year-round',
  },
  {
    name: 'SeaQuench Ale',
    slug: 'dogfish-head-seaquench',
    brewerySlug: 'dogfish-head',
    style: 'Sour Ale',
    description: 'A session sour mashup of a kolsch, gose, and Berliner weisse with lime peel, sea salt, and black limes. The ultimate beach beer.',
    abv: 4.9,
    ibu: 10,
    iqScore: 84,
    flavorTags: ['Salty', 'Lime', 'Tart', 'Refreshing', 'Crisp'],
    foodPairings: ['Ceviche', 'Fish tacos', 'Watermelon salad'],
    availability: 'Year-round',
  },

  // Bell's (4 beers)
  {
    name: 'Two Hearted Ale',
    slug: 'bells-two-hearted-ale',
    brewerySlug: 'bells',
    style: 'IPA',
    description: 'Brewed exclusively with Centennial hops for a perfectly balanced, floral, and citrusy IPA. Voted best beer in America multiple times.',
    abv: 7.0,
    ibu: 55,
    iqScore: 95,
    flavorTags: ['Grapefruit', 'Floral', 'Balanced', 'Clean', 'Pine'],
    foodPairings: ['Grilled salmon', 'Gorgonzola', 'Thai curry'],
    availability: 'Year-round',
  },
  {
    name: 'Oberon Ale',
    slug: 'bells-oberon',
    brewerySlug: 'bells',
    style: 'Wheat Ale',
    description: 'The iconic American wheat ale that signals summer in the Midwest. Light, citrusy, and incredibly refreshing.',
    abv: 5.8,
    ibu: 12,
    iqScore: 85,
    flavorTags: ['Citrus', 'Wheat', 'Refreshing', 'Light', 'Summer'],
    foodPairings: ['Grilled chicken', 'Summer salads', 'Light pasta'],
    availability: 'Seasonal',
  },
  {
    name: 'Hopslam Ale',
    slug: 'bells-hopslam',
    brewerySlug: 'bells',
    style: 'Imperial IPA',
    description: 'A hugely aromatic double IPA brewed with six hop varieties and honey. An annual January release that sells out instantly.',
    abv: 10.0,
    ibu: 70,
    iqScore: 91,
    flavorTags: ['Hoppy', 'Honey', 'Complex', 'Strong', 'Tropical'],
    foodPairings: ['Spicy wings', 'Strong aged cheese', 'Cheesecake'],
    availability: 'Limited',
  },
  {
    name: 'Expedition Stout',
    slug: 'bells-expedition-stout',
    brewerySlug: 'bells',
    style: 'Russian Imperial Stout',
    description: 'A massive imperial stout with espresso-like roastiness and dark fruit complexity. Ages gracefully for a decade or more.',
    abv: 10.5,
    ibu: 60,
    iqScore: 89,
    flavorTags: ['Roast', 'Coffee', 'Chocolate', 'Complex', 'Warming'],
    foodPairings: ['Dark chocolate truffles', 'Coffee cake', 'Smoked brisket'],
    availability: 'Seasonal',
  },

  // Founders (5 beers)
  {
    name: 'All Day IPA',
    slug: 'founders-all-day-ipa',
    brewerySlug: 'founders',
    style: 'Session IPA',
    description: 'The beer that proved session IPAs could have real flavor. Light, crushable, and full of hop character at only 4.7% ABV.',
    abv: 4.7,
    ibu: 42,
    iqScore: 83,
    flavorTags: ['Sessionable', 'Citrus', 'Light', 'Crisp', 'Hoppy'],
    foodPairings: ['Grilled chicken wings', 'Fish tacos', 'Mixed nuts'],
    availability: 'Year-round',
  },
  {
    name: 'KBS (Kentucky Breakfast Stout)',
    slug: 'founders-kbs',
    brewerySlug: 'founders',
    style: 'Imperial Stout',
    description: 'Cave-aged in bourbon barrels for a year. Rich coffee and chocolate flavors mingle with vanilla and oak from the bourbon barrels. A legendary annual release.',
    abv: 12.0,
    ibu: 70,
    iqScore: 96,
    flavorTags: ['Bourbon', 'Vanilla', 'Coffee', 'Chocolate', 'Oak'],
    foodPairings: ['Chocolate lava cake', 'Vanilla ice cream', 'Espresso'],
    availability: 'Limited',
  },
  {
    name: 'Centennial IPA',
    slug: 'founders-centennial-ipa',
    brewerySlug: 'founders',
    style: 'IPA',
    description: 'A well-balanced IPA with floral and citrus hop character from generous Centennial hop additions throughout the brewing process.',
    abv: 7.2,
    ibu: 65,
    iqScore: 84,
    flavorTags: ['Floral', 'Citrus', 'Balanced', 'Hoppy'],
    foodPairings: ['Grilled pork chops', 'Jalape\u00f1o poppers', 'Manchego'],
    availability: 'Year-round',
  },
  {
    name: 'Breakfast Stout',
    slug: 'founders-breakfast-stout',
    brewerySlug: 'founders',
    style: 'Imperial Stout',
    description: 'Double chocolate coffee oatmeal stout brewed with flaked oats, Sumatra and Kona coffee, and imported chocolate. The non-barrel-aged sibling to KBS.',
    abv: 8.3,
    ibu: 60,
    iqScore: 90,
    flavorTags: ['Coffee', 'Chocolate', 'Oatmeal', 'Roast', 'Smooth'],
    foodPairings: ['Chocolate pancakes', 'Tiramisu', 'Bacon'],
    availability: 'Seasonal',
  },
  {
    name: 'Dirty Bastard',
    slug: 'founders-dirty-bastard',
    brewerySlug: 'founders',
    style: 'Scotch Ale',
    description: 'A complex Scotch-style ale with smoky peat malt, caramel sweetness, and a warming finish. Dark fruit and toffee notes abound.',
    abv: 8.5,
    ibu: 50,
    iqScore: 81,
    flavorTags: ['Smoky', 'Toffee', 'Caramel', 'Malty', 'Dark Fruit'],
    foodPairings: ['Smoked salmon', 'Shepherd\'s pie', 'Stilton cheese'],
    availability: 'Year-round',
  },

  // Stone (4 beers)
  {
    name: 'Stone IPA',
    slug: 'stone-ipa',
    brewerySlug: 'stone',
    style: 'IPA',
    description: 'The beer that defined West Coast IPA. Aggressively hopped with a dry, crisp finish and bold citrus and pine character.',
    abv: 6.9,
    ibu: 71,
    iqScore: 82,
    flavorTags: ['Pine', 'Bitter', 'Crisp', 'Citrus', 'Dry'],
    foodPairings: ['Spicy nachos', 'Grilled steak', 'Pepper jack'],
    availability: 'Year-round',
  },
  {
    name: 'Arrogant Bastard Ale',
    slug: 'stone-arrogant-bastard',
    brewerySlug: 'stone',
    style: 'Strong Ale',
    description: 'An aggressively bold ale that dares you not to like it. Rich malt character with intense hop bitterness and a defiant spirit.',
    abv: 7.2,
    ibu: 100,
    iqScore: 78,
    flavorTags: ['Bitter', 'Malty', 'Bold', 'Aggressive', 'Caramel'],
    foodPairings: ['Smoked brisket', 'Blue cheese', 'Dark chocolate'],
    availability: 'Year-round',
  },
  {
    name: 'Stone Delicious IPA',
    slug: 'stone-delicious-ipa',
    brewerySlug: 'stone',
    style: 'IPA',
    description: 'A gluten-reduced IPA with citrus and tropical hop character. More approachable than Stone IPA with bright lemon and tropical notes.',
    abv: 7.7,
    ibu: 75,
    iqScore: 79,
    flavorTags: ['Tropical', 'Lemon', 'Hoppy', 'Crisp'],
    foodPairings: ['Grilled chicken', 'Citrus salad', 'Goat cheese'],
    availability: 'Year-round',
  },
  {
    name: 'Stone Enjoy By IPA',
    slug: 'stone-enjoy-by',
    brewerySlug: 'stone',
    style: 'Double IPA',
    description: 'The freshest IPA you can find, with a drink-by date proudly stamped on every bottle. Explosively hoppy and meant to be consumed immediately.',
    abv: 9.4,
    ibu: 90,
    iqScore: 87,
    flavorTags: ['Tropical', 'Citrus', 'Pine', 'Intense', 'Fresh'],
    foodPairings: ['Spicy Thai curry', 'Blue cheese burger', 'Mango salsa'],
    availability: 'Limited',
  },

  // Deschutes (4 beers)
  {
    name: 'Fresh Squeezed IPA',
    slug: 'deschutes-fresh-squeezed',
    brewerySlug: 'deschutes',
    style: 'IPA',
    description: 'Juicy and refreshing with bright citrus and grapefruit hop character. One of the most popular IPAs in the Pacific Northwest.',
    abv: 6.4,
    ibu: 60,
    iqScore: 85,
    flavorTags: ['Grapefruit', 'Juicy', 'Citrus', 'Refreshing'],
    foodPairings: ['Grilled fish', 'Citrus salad', 'Soft pretzels'],
    availability: 'Year-round',
  },
  {
    name: 'Black Butte Porter',
    slug: 'deschutes-black-butte-porter',
    brewerySlug: 'deschutes',
    style: 'Porter',
    description: 'The flagship that started it all. Smooth and creamy with chocolate and coffee notes. The best-selling craft porter in America.',
    abv: 5.5,
    ibu: 30,
    iqScore: 83,
    flavorTags: ['Chocolate', 'Coffee', 'Smooth', 'Creamy'],
    foodPairings: ['Chocolate brownies', 'BBQ pork', 'Smoked gouda'],
    availability: 'Year-round',
  },
  {
    name: 'Mirror Pond Pale Ale',
    slug: 'deschutes-mirror-pond',
    brewerySlug: 'deschutes',
    style: 'Pale Ale',
    description: 'A classic American pale ale with Cascade hop character. Crisp, clean, and beautifully balanced.',
    abv: 5.0,
    ibu: 40,
    iqScore: 80,
    flavorTags: ['Citrus', 'Floral', 'Balanced', 'Crisp'],
    foodPairings: ['Grilled vegetables', 'Fish and chips', 'Brie'],
    availability: 'Year-round',
  },
  {
    name: 'The Abyss',
    slug: 'deschutes-the-abyss',
    brewerySlug: 'deschutes',
    style: 'Imperial Stout',
    description: 'An annual release aged in bourbon, wine, and new oak barrels with licorice and cherry bark. Deep, complex, and cellar-worthy.',
    abv: 11.1,
    ibu: 86,
    iqScore: 93,
    flavorTags: ['Bourbon', 'Licorice', 'Complex', 'Chocolate', 'Dark Fruit'],
    foodPairings: ['Dark chocolate', 'Aged stilton', 'Cr\u00e8me br\u00fbl\u00e9e'],
    availability: 'Limited',
  },

  // Lagunitas (3 beers)
  {
    name: 'Lagunitas IPA',
    slug: 'lagunitas-ipa',
    brewerySlug: 'lagunitas',
    style: 'IPA',
    description: 'A well-rounded IPA with a huge hop character balanced by caramel malt sweetness. A gateway IPA for many craft drinkers.',
    abv: 6.2,
    ibu: 51,
    iqScore: 81,
    flavorTags: ['Citrus', 'Pine', 'Caramel', 'Balanced'],
    foodPairings: ['Pizza', 'Grilled burger', 'Cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Lagunitas Little Sumpin',
    slug: 'lagunitas-little-sumpin',
    brewerySlug: 'lagunitas',
    style: 'Wheat IPA',
    description: 'A uniquely hoppy wheat ale with smooth, hazy body and bright tropical hop character. Not quite a wheat beer, not quite an IPA.',
    abv: 7.5,
    ibu: 64,
    iqScore: 82,
    flavorTags: ['Tropical', 'Wheat', 'Smooth', 'Hoppy'],
    foodPairings: ['Grilled shrimp', 'Pad Thai', 'Fruit salad'],
    availability: 'Year-round',
  },
  {
    name: 'Lagunitas Maximus',
    slug: 'lagunitas-maximus',
    brewerySlug: 'lagunitas',
    style: 'Imperial IPA',
    description: 'A colossal imperial IPA with assertive hop character and rich malt body. Big, bold, and unapologetically hoppy.',
    abv: 8.2,
    ibu: 78,
    iqScore: 80,
    flavorTags: ['Bold', 'Pine', 'Citrus', 'Malty', 'Warming'],
    foodPairings: ['Spicy curry', 'Strong cheese', 'Grilled lamb'],
    availability: 'Year-round',
  },

  // New Belgium (3 beers)
  {
    name: 'Fat Tire Amber Ale',
    slug: 'new-belgium-fat-tire',
    brewerySlug: 'new-belgium',
    style: 'Amber Ale',
    description: 'The flagship amber ale inspired by a bicycle trip through Belgium. Balanced, biscuity, and approachable with subtle hop character.',
    abv: 5.2,
    ibu: 22,
    iqScore: 77,
    flavorTags: ['Biscuit', 'Caramel', 'Balanced', 'Smooth'],
    foodPairings: ['Grilled chicken', 'Mac and cheese', 'Mushroom pizza'],
    availability: 'Year-round',
  },
  {
    name: 'Voodoo Ranger IPA',
    slug: 'new-belgium-voodoo-ranger',
    brewerySlug: 'new-belgium',
    style: 'IPA',
    description: 'A juicy, tropically charged IPA with bright citrus and stone fruit hop flavors. One of the best-selling IPAs in the country.',
    abv: 7.0,
    ibu: 50,
    iqScore: 79,
    flavorTags: ['Tropical', 'Citrus', 'Juicy', 'Hoppy'],
    foodPairings: ['Tacos', 'Spicy wings', 'Jalape\u00f1o poppers'],
    availability: 'Year-round',
  },
  {
    name: 'La Folie',
    slug: 'new-belgium-la-folie',
    brewerySlug: 'new-belgium',
    style: 'Flanders Red',
    description: 'A wood-aged sour beer with complex tart cherry, plum, and vinous character. One of the pioneering American sour ales.',
    abv: 7.0,
    ibu: 18,
    iqScore: 88,
    flavorTags: ['Tart', 'Cherry', 'Complex', 'Vinous', 'Oak'],
    foodPairings: ['Roasted duck', 'Brie', 'Dark chocolate'],
    availability: 'Limited',
  },

  // Firestone Walker (4 beers)
  {
    name: 'Firestone Walker Union Jack',
    slug: 'firestone-walker-union-jack',
    brewerySlug: 'firestone-walker',
    style: 'IPA',
    description: 'A West Coast IPA that achieves remarkable balance between aggressive hop character and clean malt support. Piney, crisp, and dry.',
    abv: 7.0,
    ibu: 70,
    iqScore: 86,
    flavorTags: ['Pine', 'Citrus', 'Crisp', 'Dry', 'Balanced'],
    foodPairings: ['Grilled steak', 'Spicy sausage', 'Aged cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Parabola',
    slug: 'firestone-walker-parabola',
    brewerySlug: 'firestone-walker',
    style: 'Imperial Stout',
    description: 'A barrel-aged imperial oatmeal stout of extraordinary complexity. Bourbon, dark chocolate, and espresso in perfect harmony. One of the greatest barrel-aged stouts ever produced.',
    abv: 14.0,
    ibu: 50,
    iqScore: 97,
    flavorTags: ['Bourbon', 'Chocolate', 'Vanilla', 'Espresso', 'Oak'],
    foodPairings: ['Dark chocolate truffles', 'Vanilla bean ice cream', 'Smoked ribs'],
    availability: 'Limited',
  },
  {
    name: 'Mind Haze',
    slug: 'firestone-walker-mind-haze',
    brewerySlug: 'firestone-walker',
    style: 'Hazy IPA',
    description: 'A hazy IPA brewed with lupulin powder for intense tropical hop character without harsh bitterness. Smooth, juicy, and aromatic.',
    abv: 6.2,
    ibu: 40,
    iqScore: 83,
    flavorTags: ['Tropical', 'Juicy', 'Smooth', 'Hazy'],
    foodPairings: ['Fish tacos', 'Mango salsa', 'Grilled shrimp'],
    availability: 'Year-round',
  },
  {
    name: '805',
    slug: 'firestone-walker-805',
    brewerySlug: 'firestone-walker',
    style: 'Blonde Ale',
    description: 'A refreshing blonde ale named after the California Central Coast area code. Light, easy-drinking, and perfect for the beach.',
    abv: 4.7,
    ibu: 15,
    iqScore: 74,
    flavorTags: ['Light', 'Crisp', 'Refreshing', 'Sessionable'],
    foodPairings: ['Fish tacos', 'Grilled chicken', 'Fresh fruit'],
    availability: 'Year-round',
  },

  // Russian River (4 beers)
  {
    name: 'Pliny the Elder',
    slug: 'russian-river-pliny-the-elder',
    brewerySlug: 'russian-river',
    style: 'Double IPA',
    description: 'Often called the best double IPA in the world. Remarkably balanced with complex hop character and a dry, clean finish despite its strength.',
    abv: 8.0,
    ibu: 100,
    iqScore: 97,
    flavorTags: ['Citrus', 'Pine', 'Floral', 'Crisp', 'Complex'],
    foodPairings: ['Spicy Thai', 'Strong aged cheese', 'Grilled lobster'],
    availability: 'Year-round',
  },
  {
    name: 'Pliny the Younger',
    slug: 'russian-river-pliny-the-younger',
    brewerySlug: 'russian-river',
    style: 'Triple IPA',
    description: 'The legendary annual release that draws lines around the block. A triple IPA that somehow drinks with the smoothness of a single.',
    abv: 10.25,
    ibu: 100,
    iqScore: 98,
    flavorTags: ['Tropical', 'Smooth', 'Complex', 'Intense', 'Layered'],
    foodPairings: ['Spicy curry', 'Aged gruyere', 'Lobster bisque'],
    availability: 'Limited',
  },
  {
    name: 'Supplication',
    slug: 'russian-river-supplication',
    brewerySlug: 'russian-river',
    style: 'Sour Ale',
    description: 'A complex brown ale aged in Pinot Noir barrels with cherries and wild yeast. Tart, vinous, and beautifully funky.',
    abv: 7.0,
    ibu: 10,
    iqScore: 92,
    flavorTags: ['Cherry', 'Vinous', 'Tart', 'Funky', 'Oak'],
    foodPairings: ['Roasted duck', 'Brie', 'Dark chocolate mousse'],
    availability: 'Limited',
  },
  {
    name: 'Blind Pig IPA',
    slug: 'russian-river-blind-pig',
    brewerySlug: 'russian-river',
    style: 'IPA',
    description: 'The original recipe that preceded Pliny the Elder. A wonderfully balanced IPA with bright hop character and a dry finish.',
    abv: 6.1,
    ibu: 70,
    iqScore: 90,
    flavorTags: ['Floral', 'Citrus', 'Pine', 'Balanced', 'Dry'],
    foodPairings: ['Grilled salmon', 'Goat cheese', 'Bruschetta'],
    availability: 'Year-round',
  },

  // Tree House (4 beers)
  {
    name: 'Julius',
    slug: 'tree-house-julius',
    brewerySlug: 'tree-house',
    style: 'NEIPA',
    description: 'The beer that put Tree House on the map. An incredibly juicy, tropical New England IPA with a pillowy soft mouthfeel.',
    abv: 6.8,
    ibu: 45,
    iqScore: 96,
    flavorTags: ['Tropical', 'Juicy', 'Creamy', 'Smooth', 'Mango'],
    foodPairings: ['Fish tacos', 'Fruit salad', 'Grilled chicken'],
    availability: 'Year-round',
  },
  {
    name: 'Green',
    slug: 'tree-house-green',
    brewerySlug: 'tree-house',
    style: 'NEIPA',
    description: 'A companion to Julius with a different hop blend featuring honeydew melon and citrus notes. Equally creamy and soft.',
    abv: 7.6,
    ibu: 50,
    iqScore: 93,
    flavorTags: ['Honeydew', 'Citrus', 'Creamy', 'Tropical', 'Soft'],
    foodPairings: ['Sushi', 'Mango salsa', 'Grilled shrimp'],
    availability: 'Year-round',
  },
  {
    name: 'Very Green',
    slug: 'tree-house-very-green',
    brewerySlug: 'tree-house',
    style: 'Double NEIPA',
    description: 'An amplified version of Green with more hops, more body, and more intensity. A massive double NEIPA that still drinks smooth.',
    abv: 8.3,
    ibu: 60,
    iqScore: 93,
    flavorTags: ['Intense', 'Tropical', 'Creamy', 'Bold', 'Juicy'],
    foodPairings: ['Spicy Thai', 'Strong cheese', 'Tropical fruit'],
    availability: 'Limited',
  },
  {
    name: 'Bright',
    slug: 'tree-house-bright',
    brewerySlug: 'tree-house',
    style: 'Pale Ale',
    description: 'A hop-forward pale ale that showcases citrus and tropical hop character in a lighter, more approachable package.',
    abv: 5.6,
    ibu: 35,
    iqScore: 89,
    flavorTags: ['Citrus', 'Tropical', 'Crisp', 'Light', 'Fresh'],
    foodPairings: ['Grilled chicken', 'Fresh salad', 'Light pasta'],
    availability: 'Year-round',
  },

  // The Alchemist (3 beers)
  {
    name: 'Heady Topper',
    slug: 'alchemist-heady-topper',
    brewerySlug: 'alchemist',
    style: 'Double IPA',
    description: 'The original hazy IPA that launched a revolution. Meant to be drunk from the can for maximum hop aroma. Tropical, dank, and perfectly balanced.',
    abv: 8.0,
    ibu: 75,
    iqScore: 96,
    flavorTags: ['Tropical', 'Dank', 'Smooth', 'Pine', 'Citrus'],
    foodPairings: ['Spicy Thai', 'Strong cheese', 'Grilled sausage'],
    availability: 'Year-round',
  },
  {
    name: 'Focal Banger',
    slug: 'alchemist-focal-banger',
    brewerySlug: 'alchemist',
    style: 'IPA',
    description: 'The more approachable sibling to Heady Topper. Mosaic and Citra hops create bright tropical fruit character with a clean finish.',
    abv: 7.0,
    ibu: 60,
    iqScore: 93,
    flavorTags: ['Tropical', 'Mango', 'Smooth', 'Clean', 'Citrus'],
    foodPairings: ['Fish tacos', 'Grilled shrimp', 'Fruit salad'],
    availability: 'Year-round',
  },
  {
    name: 'Crusher',
    slug: 'alchemist-crusher',
    brewerySlug: 'alchemist',
    style: 'Double IPA',
    description: 'An unfiltered double IPA bursting with Citra, Mosaic, and Galaxy hops. Massively tropical with a soft, pillowy body.',
    abv: 8.0,
    ibu: 70,
    iqScore: 91,
    flavorTags: ['Tropical', 'Juicy', 'Hazy', 'Intense', 'Soft'],
    foodPairings: ['Spicy curry', 'Grilled chicken', 'Aged cheddar'],
    availability: 'Limited',
  },

  // Other Half (3 beers)
  {
    name: 'Green City',
    slug: 'other-half-green-city',
    brewerySlug: 'other-half',
    style: 'NEIPA',
    description: 'Other Half\'s flagship hazy IPA. Bursting with tropical fruit and citrus character. Soft, juicy, and incredibly drinkable.',
    abv: 7.4,
    ibu: 50,
    iqScore: 91,
    flavorTags: ['Juicy', 'Tropical', 'Soft', 'Hazy', 'Citrus'],
    foodPairings: ['Fish tacos', 'Ceviche', 'Grilled chicken'],
    availability: 'Year-round',
  },
  {
    name: 'DDH All Citra Everything',
    slug: 'other-half-ddh-all-citra-everything',
    brewerySlug: 'other-half',
    style: 'Imperial NEIPA',
    description: 'A double dry-hopped showcase for Citra hops. Intensely citrusy with grapefruit, tangerine, and mango in a massive, juicy package.',
    abv: 8.5,
    ibu: 55,
    iqScore: 93,
    flavorTags: ['Citrus', 'Grapefruit', 'Mango', 'Intense', 'Juicy'],
    foodPairings: ['Spicy Thai', 'Mango salsa', 'Strong cheese'],
    availability: 'Limited',
  },
  {
    name: 'Dream in Green',
    slug: 'other-half-dream-in-green',
    brewerySlug: 'other-half',
    style: 'NEIPA',
    description: 'A lush, tropical IPA with layers of hop character. Nelson Sauvin and Citra hops create wine-like grape and citrus notes.',
    abv: 6.8,
    ibu: 45,
    iqScore: 89,
    flavorTags: ['Grape', 'Tropical', 'Citrus', 'Smooth', 'Complex'],
    foodPairings: ['Sushi', 'Grilled shrimp', 'Fresh mozzarella'],
    availability: 'Limited',
  },

  // Trillium (3 beers)
  {
    name: 'Congress Street IPA',
    slug: 'trillium-congress-street',
    brewerySlug: 'trillium',
    style: 'NEIPA',
    description: 'Trillium\'s flagship year-round NEIPA. Tangerine and pineapple hop character with a creamy, full body and bright finish.',
    abv: 7.2,
    ibu: 50,
    iqScore: 92,
    flavorTags: ['Tangerine', 'Pineapple', 'Creamy', 'Hazy', 'Bright'],
    foodPairings: ['Grilled fish', 'Tropical fruit salad', 'Soft pretzels'],
    availability: 'Year-round',
  },
  {
    name: 'DDH Fort Point',
    slug: 'trillium-ddh-fort-point',
    brewerySlug: 'trillium',
    style: 'Pale Ale',
    description: 'A double dry-hopped pale ale with peach and citrus character. Lighter and more sessionable than their IPAs but equally flavorful.',
    abv: 6.6,
    ibu: 40,
    iqScore: 89,
    flavorTags: ['Peach', 'Citrus', 'Light', 'Refreshing', 'Hoppy'],
    foodPairings: ['Grilled chicken', 'Summer salad', 'Light pasta'],
    availability: 'Year-round',
  },
  {
    name: 'Permutation Series #45',
    slug: 'trillium-permutation-45',
    brewerySlug: 'trillium',
    style: 'Wild Ale',
    description: 'Part of Trillium\'s wild ale series. A mixed-fermentation ale with complex funky and fruity character from extended barrel aging.',
    abv: 6.5,
    ibu: 10,
    iqScore: 90,
    flavorTags: ['Funky', 'Tart', 'Complex', 'Fruity', 'Oak'],
    foodPairings: ['Charcuterie', 'Aged cheese', 'Roasted duck'],
    availability: 'Limited',
  },

  // Modern Times (3 beers)
  {
    name: 'Blazing World',
    slug: 'modern-times-blazing-world',
    brewerySlug: 'modern-times',
    style: 'Amber IPA',
    description: 'A hoppy amber ale with a unique combination of rich malt character and bold hop flavor. Pine, citrus, and caramel in harmony.',
    abv: 6.8,
    ibu: 80,
    iqScore: 85,
    flavorTags: ['Pine', 'Caramel', 'Citrus', 'Bold', 'Hoppy'],
    foodPairings: ['BBQ ribs', 'Aged cheddar', 'Spicy sausage'],
    availability: 'Year-round',
  },
  {
    name: 'Black House',
    slug: 'modern-times-black-house',
    brewerySlug: 'modern-times',
    style: 'Coffee Stout',
    description: 'A creamy oatmeal coffee stout brewed with Modern Times\' own roasted coffee. Rich, smooth, and perfectly caffeinated.',
    abv: 5.8,
    ibu: 30,
    iqScore: 86,
    flavorTags: ['Coffee', 'Chocolate', 'Creamy', 'Smooth', 'Roast'],
    foodPairings: ['Chocolate cake', 'Tiramisu', 'Breakfast burrito'],
    availability: 'Year-round',
  },
  {
    name: 'Orderville',
    slug: 'modern-times-orderville',
    brewerySlug: 'modern-times',
    style: 'Hazy IPA',
    description: 'A hazy IPA with Citra and Mosaic hops delivering bright tropical and citrus character. Soft, juicy, and incredibly drinkable.',
    abv: 7.2,
    ibu: 45,
    iqScore: 87,
    flavorTags: ['Tropical', 'Citrus', 'Juicy', 'Hazy', 'Soft'],
    foodPairings: ['Fish tacos', 'Grilled chicken', 'Mango salsa'],
    availability: 'Year-round',
  },

  // Cigar City (3 beers)
  {
    name: 'Jai Alai IPA',
    slug: 'cigar-city-jai-alai',
    brewerySlug: 'cigar-city',
    style: 'IPA',
    description: 'An assertive American IPA with huge citrus and tropical hop character. Bold, balanced, and the pride of Tampa\'s craft beer scene.',
    abv: 7.5,
    ibu: 70,
    iqScore: 86,
    flavorTags: ['Citrus', 'Tropical', 'Bold', 'Balanced', 'Pine'],
    foodPairings: ['Cuban sandwich', 'Spicy wings', 'Grilled mahi-mahi'],
    availability: 'Year-round',
  },
  {
    name: 'Hunahpu\'s Imperial Stout',
    slug: 'cigar-city-hunahpus',
    brewerySlug: 'cigar-city',
    style: 'Imperial Stout',
    description: 'An imperial stout brewed with ancho and pasilla chili peppers, cacao nibs, cinnamon, and vanilla. A Mexican hot chocolate in beer form.',
    abv: 11.0,
    ibu: 45,
    iqScore: 94,
    flavorTags: ['Chocolate', 'Cinnamon', 'Chili', 'Vanilla', 'Warming'],
    foodPairings: ['Mole sauce', 'Dark chocolate truffles', 'Churros'],
    availability: 'Limited',
  },
  {
    name: 'Florida Cracker',
    slug: 'cigar-city-florida-cracker',
    brewerySlug: 'cigar-city',
    style: 'Belgian-Style Witbier',
    description: 'A refreshing Belgian-style white ale brewed with orange peel and coriander. Light, zesty, and perfect for Florida\'s tropical climate.',
    abv: 5.5,
    ibu: 15,
    iqScore: 78,
    flavorTags: ['Citrus', 'Coriander', 'Light', 'Refreshing', 'Wheat'],
    foodPairings: ['Ceviche', 'Light salads', 'Grilled shrimp'],
    availability: 'Year-round',
  },

  // Prairie Artisan (3 beers)
  {
    name: 'Prairie BOMB!',
    slug: 'prairie-bomb',
    brewerySlug: 'prairie-artisan',
    style: 'Imperial Stout',
    description: 'An imperial stout aged on espresso beans, vanilla, cacao nibs, and ancho chili peppers. Rich, complex, and explosive with flavor.',
    abv: 13.0,
    ibu: 65,
    iqScore: 91,
    flavorTags: ['Espresso', 'Vanilla', 'Chocolate', 'Chili', 'Complex'],
    foodPairings: ['Dark chocolate', 'Espresso desserts', 'Mole chicken'],
    availability: 'Year-round',
  },
  {
    name: 'Prairie Artisan Ale',
    slug: 'prairie-artisan-ale',
    brewerySlug: 'prairie-artisan',
    style: 'Farmhouse Ale',
    description: 'A classic American farmhouse ale with bright citrus and peppery yeast character. Dry, refreshing, and effervescent.',
    abv: 5.0,
    ibu: 20,
    iqScore: 83,
    flavorTags: ['Peppery', 'Citrus', 'Dry', 'Farmhouse', 'Effervescent'],
    foodPairings: ['Goat cheese salad', 'Grilled chicken', 'Fresh bread'],
    availability: 'Year-round',
  },
  {
    name: 'Prairie Noir',
    slug: 'prairie-noir',
    brewerySlug: 'prairie-artisan',
    style: 'Barrel-Aged Imperial Stout',
    description: 'A bourbon barrel-aged imperial stout with rich dark chocolate, vanilla, and oak character. Silky smooth and deeply satisfying.',
    abv: 12.5,
    ibu: 50,
    iqScore: 90,
    flavorTags: ['Bourbon', 'Chocolate', 'Vanilla', 'Oak', 'Silky'],
    foodPairings: ['Vanilla ice cream', 'Dark chocolate', 'Pecan pie'],
    availability: 'Limited',
  },

  // Toppling Goliath (3 beers)
  {
    name: 'King Sue',
    slug: 'toppling-goliath-king-sue',
    brewerySlug: 'toppling-goliath',
    style: 'Double IPA',
    description: 'A double dry-hopped imperial IPA showcasing Citra hops. Massive tropical fruit character with mango, papaya, and citrus.',
    abv: 7.8,
    ibu: 65,
    iqScore: 94,
    flavorTags: ['Mango', 'Tropical', 'Juicy', 'Citrus', 'Intense'],
    foodPairings: ['Spicy Thai', 'Tropical fruit', 'Grilled chicken'],
    availability: 'Year-round',
  },
  {
    name: 'PseudoSue',
    slug: 'toppling-goliath-pseudosue',
    brewerySlug: 'toppling-goliath',
    style: 'Pale Ale',
    description: 'A single-hop Citra pale ale that showcases tropical and citrus character in a lighter, more sessionable package. Smooth and crushable.',
    abv: 5.8,
    ibu: 50,
    iqScore: 89,
    flavorTags: ['Tropical', 'Citrus', 'Smooth', 'Crisp', 'Citra'],
    foodPairings: ['Fish tacos', 'Grilled chicken', 'Light salads'],
    availability: 'Year-round',
  },
  {
    name: 'Mornin\' Delight',
    slug: 'toppling-goliath-mornin-delight',
    brewerySlug: 'toppling-goliath',
    style: 'Imperial Stout',
    description: 'A legendary barrel-aged imperial stout with maple syrup and coffee. One of the highest-rated beers in the world with a devoted cult following.',
    abv: 12.0,
    ibu: 50,
    iqScore: 98,
    flavorTags: ['Maple', 'Coffee', 'Bourbon', 'Vanilla', 'Complex'],
    foodPairings: ['Pancakes', 'Dark chocolate', 'Vanilla bean ice cream'],
    availability: 'Limited',
  },

  // 3 Floyds (3 beers)
  {
    name: 'Zombie Dust',
    slug: '3-floyds-zombie-dust',
    brewerySlug: '3-floyds',
    style: 'Pale Ale',
    description: 'An intensely hopped pale ale with Citra hops delivering vivid citrus and tropical notes. One of the most sought-after pale ales in America.',
    abv: 6.2,
    ibu: 50,
    iqScore: 92,
    flavorTags: ['Citrus', 'Tropical', 'Hoppy', 'Balanced', 'Fresh'],
    foodPairings: ['Pizza', 'Grilled chicken', 'Sharp cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Dark Lord',
    slug: '3-floyds-dark-lord',
    brewerySlug: '3-floyds',
    style: 'Russian Imperial Stout',
    description: 'A massive imperial stout brewed with coffee, Indian sugar, and Mexican vanilla. Released once a year at Dark Lord Day. Thick, intense, and legendary.',
    abv: 15.0,
    ibu: 50,
    iqScore: 93,
    flavorTags: ['Molasses', 'Coffee', 'Dark Fruit', 'Intense', 'Complex'],
    foodPairings: ['Dark chocolate', 'Smoked brisket', 'Tiramisu'],
    availability: 'Limited',
  },
  {
    name: 'Gumballhead',
    slug: '3-floyds-gumballhead',
    brewerySlug: '3-floyds',
    style: 'American Wheat Ale',
    description: 'An American wheat ale hopped with Amarillo for bright citrus and floral character. Refreshing, approachable, and perfect for summer.',
    abv: 5.6,
    ibu: 35,
    iqScore: 85,
    flavorTags: ['Citrus', 'Wheat', 'Floral', 'Refreshing', 'Light'],
    foodPairings: ['Grilled fish', 'Summer salads', 'Light cheese'],
    availability: 'Year-round',
  },

  // Half Acre (3 beers)
  {
    name: 'Daisy Cutter Pale Ale',
    slug: 'half-acre-daisy-cutter',
    brewerySlug: 'half-acre',
    style: 'Pale Ale',
    description: 'A hop-heavy pale ale that put Half Acre on the map. Bold Centennial and Simcoe hop character with a clean, dry finish.',
    abv: 5.2,
    ibu: 55,
    iqScore: 85,
    flavorTags: ['Citrus', 'Pine', 'Dry', 'Hoppy', 'Crisp'],
    foodPairings: ['Deep dish pizza', 'Grilled burger', 'Cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Gone Away IPA',
    slug: 'half-acre-gone-away',
    brewerySlug: 'half-acre',
    style: 'IPA',
    description: 'A West Coast-style IPA with bright citrus and tropical hop character. Clean, crisp, and intensely aromatic.',
    abv: 7.0,
    ibu: 68,
    iqScore: 84,
    flavorTags: ['Citrus', 'Tropical', 'Crisp', 'Pine', 'Aromatic'],
    foodPairings: ['Spicy tacos', 'Grilled chicken', 'Sharp cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Bodem',
    slug: 'half-acre-bodem',
    brewerySlug: 'half-acre',
    style: 'IPA',
    description: 'A hazy IPA with lush tropical fruit character. Citra and Galaxy hops deliver mango, passionfruit, and citrus in a soft, full body.',
    abv: 6.5,
    ibu: 45,
    iqScore: 86,
    flavorTags: ['Mango', 'Passionfruit', 'Citrus', 'Hazy', 'Soft'],
    foodPairings: ['Sushi', 'Grilled shrimp', 'Mango salsa'],
    availability: 'Year-round',
  },

  // Surly (3 beers)
  {
    name: 'Furious',
    slug: 'surly-furious',
    brewerySlug: 'surly',
    style: 'IPA',
    description: 'An aggressively hopped West Coast IPA that helped change Minnesota beer culture. Bold citrus and pine with a strong malt backbone.',
    abv: 6.6,
    ibu: 99,
    iqScore: 85,
    flavorTags: ['Citrus', 'Pine', 'Bold', 'Aggressive', 'Malty'],
    foodPairings: ['Spicy wings', 'Grilled burger', 'Pepper jack'],
    availability: 'Year-round',
  },
  {
    name: 'Darkness',
    slug: 'surly-darkness',
    brewerySlug: 'surly',
    style: 'Russian Imperial Stout',
    description: 'An annual release Russian imperial stout with rich chocolate, coffee, and dark fruit character. The centerpiece of Darkness Day celebrations.',
    abv: 12.0,
    ibu: 100,
    iqScore: 93,
    flavorTags: ['Chocolate', 'Coffee', 'Dark Fruit', 'Cherry', 'Roast'],
    foodPairings: ['Chocolate cake', 'Smoked brisket', 'Dark chocolate'],
    availability: 'Limited',
  },
  {
    name: 'Todd the Axe Man',
    slug: 'surly-todd-the-axe-man',
    brewerySlug: 'surly',
    style: 'IPA',
    description: 'A bold IPA showcasing West Coast hop character. Bright tropical and citrus notes with a dry, satisfying finish.',
    abv: 7.2,
    ibu: 65,
    iqScore: 87,
    flavorTags: ['Tropical', 'Citrus', 'Dry', 'Bold', 'Piney'],
    foodPairings: ['Spicy sausage', 'Grilled steak', 'Aged cheddar'],
    availability: 'Year-round',
  },

  // Odell (3 beers)
  {
    name: 'Odell IPA',
    slug: 'odell-ipa',
    brewerySlug: 'odell',
    style: 'IPA',
    description: 'A classic American IPA with a beautiful balance of hop bitterness and malt sweetness. Citrus and floral hop character shines.',
    abv: 7.0,
    ibu: 60,
    iqScore: 82,
    flavorTags: ['Citrus', 'Floral', 'Balanced', 'Crisp'],
    foodPairings: ['Grilled chicken', 'Spicy tacos', 'Gouda'],
    availability: 'Year-round',
  },
  {
    name: '90 Shilling',
    slug: 'odell-90-shilling',
    brewerySlug: 'odell',
    style: 'Amber Ale',
    description: 'An award-winning amber ale with rich malt character and a clean, smooth finish. A Colorado craft beer staple since 1989.',
    abv: 5.3,
    ibu: 27,
    iqScore: 80,
    flavorTags: ['Caramel', 'Smooth', 'Malty', 'Balanced'],
    foodPairings: ['Grilled steak', 'Mushroom risotto', 'Cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Drumroll',
    slug: 'odell-drumroll',
    brewerySlug: 'odell',
    style: 'Hazy Pale Ale',
    description: 'A refreshing hazy pale ale with tropical and citrus hop character. Approachable, flavorful, and perfect for any occasion.',
    abv: 5.3,
    ibu: 30,
    iqScore: 81,
    flavorTags: ['Tropical', 'Citrus', 'Hazy', 'Refreshing', 'Light'],
    foodPairings: ['Fish tacos', 'Grilled vegetables', 'Fresh mozzarella'],
    availability: 'Year-round',
  },

  // Great Notion (3 beers)
  {
    name: 'Juice Jr.',
    slug: 'great-notion-juice-jr',
    brewerySlug: 'great-notion',
    style: 'Hazy IPA',
    description: 'A juicy, tropical hazy IPA that showcases Mosaic and Citra hops. Bright, fruity, and pillowy soft.',
    abv: 6.5,
    ibu: 40,
    iqScore: 88,
    flavorTags: ['Tropical', 'Juicy', 'Citrus', 'Soft', 'Hazy'],
    foodPairings: ['Fish tacos', 'Tropical fruit salad', 'Grilled chicken'],
    availability: 'Year-round',
  },
  {
    name: 'Blueberry Muffin',
    slug: 'great-notion-blueberry-muffin',
    brewerySlug: 'great-notion',
    style: 'Fruited Sour',
    description: 'A fruit sour conditioned on blueberries, vanilla, cinnamon, and lactose. Tastes remarkably like a freshly baked blueberry muffin.',
    abv: 5.5,
    ibu: 5,
    iqScore: 87,
    flavorTags: ['Blueberry', 'Vanilla', 'Cinnamon', 'Sweet', 'Tart'],
    foodPairings: ['Brunch', 'Pancakes', 'Fresh pastries'],
    availability: 'Year-round',
  },
  {
    name: 'Double Stack',
    slug: 'great-notion-double-stack',
    brewerySlug: 'great-notion',
    style: 'Imperial Stout',
    description: 'A pastry imperial stout brewed with maple syrup, coffee, and vanilla. Rich, decadent, and dessert-like.',
    abv: 11.0,
    ibu: 40,
    iqScore: 91,
    flavorTags: ['Maple', 'Coffee', 'Vanilla', 'Chocolate', 'Decadent'],
    foodPairings: ['Pancakes', 'Chocolate cake', 'Vanilla ice cream'],
    availability: 'Limited',
  },

  // Wicked Weed (3 beers)
  {
    name: 'Pernicious IPA',
    slug: 'wicked-weed-pernicious',
    brewerySlug: 'wicked-weed',
    style: 'IPA',
    description: 'A dangerously drinkable IPA with bright tropical and citrus hop character. The flagship that launched Wicked Weed.',
    abv: 7.3,
    ibu: 72,
    iqScore: 84,
    flavorTags: ['Tropical', 'Citrus', 'Pine', 'Bold', 'Crisp'],
    foodPairings: ['BBQ pulled pork', 'Spicy wings', 'Pepper jack'],
    availability: 'Year-round',
  },
  {
    name: 'Angel of Darkness',
    slug: 'wicked-weed-angel-of-darkness',
    brewerySlug: 'wicked-weed',
    style: 'Sour Ale',
    description: 'A dark wild ale aged in red wine barrels with dark fruit and earthy funk. Complex, tart, and hauntingly beautiful.',
    abv: 7.5,
    ibu: 10,
    iqScore: 89,
    flavorTags: ['Dark Fruit', 'Tart', 'Funky', 'Vinous', 'Oak'],
    foodPairings: ['Aged cheese', 'Roasted duck', 'Dark chocolate'],
    availability: 'Limited',
  },
  {
    name: 'Serenity',
    slug: 'wicked-weed-serenity',
    brewerySlug: 'wicked-weed',
    style: 'Farmhouse Ale',
    description: 'A dry, crisp farmhouse ale with peppery yeast character and delicate citrus notes. Refreshing and complex.',
    abv: 6.2,
    ibu: 22,
    iqScore: 82,
    flavorTags: ['Peppery', 'Dry', 'Citrus', 'Crisp', 'Farmhouse'],
    foodPairings: ['Grilled chicken', 'Goat cheese', 'Fresh salad'],
    availability: 'Seasonal',
  },

  // Boulevard (3 beers)
  {
    name: 'Tank 7 Farmhouse Ale',
    slug: 'boulevard-tank-7',
    brewerySlug: 'boulevard',
    style: 'Farmhouse Ale',
    description: 'A big, complex farmhouse ale with fruity, spicy Belgian yeast character. Named after a fermentation tank that produced unexpected results.',
    abv: 8.5,
    ibu: 38,
    iqScore: 88,
    flavorTags: ['Peppery', 'Fruity', 'Complex', 'Dry', 'Strong'],
    foodPairings: ['Grilled fish', 'Thai curry', 'Brie'],
    availability: 'Year-round',
  },
  {
    name: 'Unfiltered Wheat',
    slug: 'boulevard-unfiltered-wheat',
    brewerySlug: 'boulevard',
    style: 'Wheat Ale',
    description: 'A crisp, refreshing unfiltered American wheat ale. Boulevard\'s original flagship and the best-selling craft beer in the Midwest for years.',
    abv: 4.4,
    ibu: 14,
    iqScore: 76,
    flavorTags: ['Wheat', 'Citrus', 'Light', 'Refreshing', 'Crisp'],
    foodPairings: ['Grilled chicken', 'Light salads', 'Fish tacos'],
    availability: 'Year-round',
  },
  {
    name: 'The Calling IPA',
    slug: 'boulevard-the-calling',
    brewerySlug: 'boulevard',
    style: 'Double IPA',
    description: 'An aggressively dry-hopped double IPA with bold tropical and citrus character. Big, bold, and beautifully balanced.',
    abv: 8.5,
    ibu: 65,
    iqScore: 85,
    flavorTags: ['Tropical', 'Citrus', 'Bold', 'Dry', 'Intense'],
    foodPairings: ['Spicy Thai', 'Strong aged cheese', 'Grilled steak'],
    availability: 'Year-round',
  },

  // Left Hand (3 beers)
  {
    name: 'Milk Stout Nitro',
    slug: 'left-hand-milk-stout-nitro',
    brewerySlug: 'left-hand',
    style: 'Milk Stout',
    description: 'The first American craft beer with a widget for nitro from the bottle. Creamy, smooth, and rich with chocolate and coffee notes.',
    abv: 6.0,
    ibu: 25,
    iqScore: 84,
    flavorTags: ['Creamy', 'Chocolate', 'Coffee', 'Smooth', 'Nitro'],
    foodPairings: ['Chocolate cake', 'Grilled steak', 'Ice cream'],
    availability: 'Year-round',
  },
  {
    name: 'Sawtooth Ale',
    slug: 'left-hand-sawtooth',
    brewerySlug: 'left-hand',
    style: 'ESB',
    description: 'A balanced extra special bitter with biscuity malt character and moderate English hop bitterness. Classic and reliable.',
    abv: 5.3,
    ibu: 27,
    iqScore: 78,
    flavorTags: ['Biscuit', 'Balanced', 'Malty', 'Smooth'],
    foodPairings: ['Fish and chips', 'Roast chicken', 'Cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Fade to Black',
    slug: 'left-hand-fade-to-black',
    brewerySlug: 'left-hand',
    style: 'Foreign Stout',
    description: 'A rich and roasty foreign-style stout with dark chocolate, espresso, and dried fruit character. Bold yet balanced.',
    abv: 8.5,
    ibu: 30,
    iqScore: 83,
    flavorTags: ['Chocolate', 'Espresso', 'Roast', 'Dark Fruit', 'Bold'],
    foodPairings: ['Dark chocolate', 'Smoked brisket', 'Espresso desserts'],
    availability: 'Seasonal',
  },

  // Oskar Blues (3 beers)
  {
    name: "Dale's Pale Ale",
    slug: 'oskar-blues-dales-pale-ale',
    brewerySlug: 'oskar-blues',
    style: 'Pale Ale',
    description: 'The first craft beer in a can. Bold hop character with a solid malt backbone. Pioneered the craft canning movement.',
    abv: 6.5,
    ibu: 65,
    iqScore: 82,
    flavorTags: ['Citrus', 'Pine', 'Bold', 'Balanced', 'Crisp'],
    foodPairings: ['Grilled burger', 'Spicy wings', 'Cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Mama\'s Little Yella Pils',
    slug: 'oskar-blues-mamas-little-yella-pils',
    brewerySlug: 'oskar-blues',
    style: 'Pilsner',
    description: 'A refreshing Czech-style pilsner with noble hop character and crisp malt flavor. Light, clean, and incredibly drinkable.',
    abv: 5.3,
    ibu: 35,
    iqScore: 81,
    flavorTags: ['Crisp', 'Floral', 'Light', 'Clean', 'Balanced'],
    foodPairings: ['Grilled chicken', 'Light salads', 'Fresh bread'],
    availability: 'Year-round',
  },
  {
    name: 'Ten FIDY',
    slug: 'oskar-blues-ten-fidy',
    brewerySlug: 'oskar-blues',
    style: 'Imperial Stout',
    description: 'A massive imperial stout clocking in at 10.5% ABV. Rich with roasted malt, dark chocolate, and espresso character.',
    abv: 10.5,
    ibu: 98,
    iqScore: 89,
    flavorTags: ['Chocolate', 'Espresso', 'Roast', 'Intense', 'Bold'],
    foodPairings: ['Dark chocolate', 'Smoked ribs', 'Coffee cake'],
    availability: 'Seasonal',
  },

  // AleSmith (3 beers)
  {
    name: 'Speedway Stout',
    slug: 'alesmith-speedway-stout',
    brewerySlug: 'alesmith',
    style: 'Imperial Stout',
    description: 'A world-class imperial stout brewed with locally roasted coffee. Rich, complex, and incredibly smooth for its strength.',
    abv: 12.0,
    ibu: 70,
    iqScore: 94,
    flavorTags: ['Coffee', 'Chocolate', 'Roast', 'Smooth', 'Complex'],
    foodPairings: ['Espresso desserts', 'Dark chocolate', 'Tiramisu'],
    availability: 'Year-round',
  },
  {
    name: '.394 Pale Ale',
    slug: 'alesmith-394-pale-ale',
    brewerySlug: 'alesmith',
    style: 'Pale Ale',
    description: 'Named after Tony Gwynn\'s career batting average. A San Diego pale ale with bright hop character and a clean malt backbone.',
    abv: 6.0,
    ibu: 35,
    iqScore: 83,
    flavorTags: ['Citrus', 'Tropical', 'Balanced', 'Clean', 'Crisp'],
    foodPairings: ['Fish tacos', 'Grilled chicken', 'Light pasta'],
    availability: 'Year-round',
  },
  {
    name: 'Nut Brown Ale',
    slug: 'alesmith-nut-brown',
    brewerySlug: 'alesmith',
    style: 'English Brown Ale',
    description: 'A rich and malty English-style brown ale with toffee, caramel, and nutty character. Smooth and satisfying.',
    abv: 5.0,
    ibu: 22,
    iqScore: 81,
    flavorTags: ['Toffee', 'Caramel', 'Nutty', 'Smooth', 'Malty'],
    foodPairings: ['Roasted meat', 'Grilled mushrooms', 'Aged cheddar'],
    availability: 'Year-round',
  },

  // Revolution (3 beers)
  {
    name: 'Anti-Hero IPA',
    slug: 'revolution-anti-hero',
    brewerySlug: 'revolution',
    style: 'IPA',
    description: 'A bold American IPA with bright citrus and pine hop character. The flagship beer of Chicago\'s largest independent brewery.',
    abv: 6.5,
    ibu: 69,
    iqScore: 83,
    flavorTags: ['Citrus', 'Pine', 'Balanced', 'Crisp', 'Hoppy'],
    foodPairings: ['Deep dish pizza', 'Hot dogs', 'Sharp cheddar'],
    availability: 'Year-round',
  },
  {
    name: 'Fist City',
    slug: 'revolution-fist-city',
    brewerySlug: 'revolution',
    style: 'Pale Ale',
    description: 'A Chicago pale ale with approachable hop character and a crisp, dry finish. Sessionable and perfect for the neighborhood taproom.',
    abv: 5.5,
    ibu: 40,
    iqScore: 80,
    flavorTags: ['Citrus', 'Crisp', 'Dry', 'Light', 'Balanced'],
    foodPairings: ['Italian beef', 'Pizza', 'Grilled chicken'],
    availability: 'Year-round',
  },
  {
    name: 'Deth\'s Tar',
    slug: 'revolution-deths-tar',
    brewerySlug: 'revolution',
    style: 'Imperial Stout',
    description: 'A barrel-aged imperial oatmeal stout from the Deep Wood series. Rich with bourbon, chocolate, and vanilla character.',
    abv: 14.5,
    ibu: 55,
    iqScore: 93,
    flavorTags: ['Bourbon', 'Chocolate', 'Vanilla', 'Oak', 'Complex'],
    foodPairings: ['Dark chocolate truffles', 'Vanilla ice cream', 'Espresso'],
    availability: 'Limited',
  },

  // Montauk (3 beers)
  {
    name: 'Montauk Wave Chaser IPA',
    slug: 'montauk-wave-chaser',
    brewerySlug: 'montauk',
    style: 'IPA',
    description: 'A tropical IPA inspired by Long Island surf culture. Citrus and tropical hop character with a clean, refreshing finish.',
    abv: 6.4,
    ibu: 50,
    iqScore: 76,
    flavorTags: ['Tropical', 'Citrus', 'Refreshing', 'Clean'],
    foodPairings: ['Fish and chips', 'Lobster roll', 'Grilled shrimp'],
    availability: 'Year-round',
  },
  {
    name: 'Montauk Summer Ale',
    slug: 'montauk-summer-ale',
    brewerySlug: 'montauk',
    style: 'Wheat Ale',
    description: 'A light, refreshing wheat ale perfect for the Hamptons beach scene. Crisp, citrusy, and endlessly crushable.',
    abv: 5.0,
    ibu: 12,
    iqScore: 73,
    flavorTags: ['Light', 'Citrus', 'Wheat', 'Refreshing', 'Crisp'],
    foodPairings: ['Lobster roll', 'Oysters', 'Fresh salad'],
    availability: 'Seasonal',
  },
  {
    name: 'Montauk Pilsner',
    slug: 'montauk-pilsner',
    brewerySlug: 'montauk',
    style: 'Pilsner',
    description: 'A crisp, clean craft pilsner with noble hop character. Light and refreshing with a dry finish.',
    abv: 4.8,
    ibu: 25,
    iqScore: 74,
    flavorTags: ['Crisp', 'Clean', 'Light', 'Floral', 'Dry'],
    foodPairings: ['Grilled fish', 'Oysters', 'Light cheese'],
    availability: 'Year-round',
  },

  // Hill Farmstead (4 beers)
  {
    name: 'Edward',
    slug: 'hill-farmstead-edward',
    brewerySlug: 'hill-farmstead',
    style: 'Pale Ale',
    description: 'Named after Shaun Hill\'s grandfather. A transcendent American pale ale with crystalline hop expression and ethereal balance. Widely regarded as the finest pale ale in the world.',
    abv: 5.2,
    ibu: 45,
    iqScore: 97,
    flavorTags: ['Floral', 'Citrus', 'Clean', 'Crisp', 'Balanced'],
    foodPairings: ['Grilled trout', 'Fresh salad', 'Soft cheese'],
    availability: 'Year-round',
  },
  {
    name: 'Abner',
    slug: 'hill-farmstead-abner',
    brewerySlug: 'hill-farmstead',
    style: 'Double IPA',
    description: 'Named after Shaun Hill\'s grandfather. A refined double IPA with remarkable balance between hop intensity and drinkability. Floral and citrus notes with zero rough edges.',
    abv: 8.2,
    ibu: 70,
    iqScore: 97,
    flavorTags: ['Floral', 'Citrus', 'Refined', 'Balanced', 'Elegant'],
    foodPairings: ['Grilled lobster', 'Aged gruyere', 'Herb-crusted salmon'],
    availability: 'Year-round',
  },
  {
    name: 'Ann',
    slug: 'hill-farmstead-ann',
    brewerySlug: 'hill-farmstead',
    style: 'Farmhouse Ale',
    description: 'Named after Shaun Hill\'s aunt. A dry, effervescent saison with white pepper, hay, and stone fruit notes. A modern American farmhouse masterpiece.',
    abv: 6.0,
    ibu: 25,
    iqScore: 94,
    flavorTags: ['Peppery', 'Dry', 'Effervescent', 'Complex', 'Stone Fruit'],
    foodPairings: ['Roasted chicken', 'Goat cheese', 'Fresh bread'],
    availability: 'Seasonal',
  },
  {
    name: 'Society & Solitude #5',
    slug: 'hill-farmstead-society-solitude-5',
    brewerySlug: 'hill-farmstead',
    style: 'Double IPA',
    description: 'A double IPA from the Society & Solitude series featuring Galaxy hops. Tropical, juicy, and remarkably smooth for its strength.',
    abv: 8.0,
    ibu: 65,
    iqScore: 95,
    flavorTags: ['Tropical', 'Juicy', 'Smooth', 'Galaxy', 'Intense'],
    foodPairings: ['Spicy Thai', 'Tropical fruit', 'Grilled shrimp'],
    availability: 'Limited',
  },

  // Maine Beer Company (3 beers)
  {
    name: 'Lunch',
    slug: 'maine-beer-lunch',
    brewerySlug: 'maine-beer',
    style: 'IPA',
    description: 'Clean, precise, and endlessly drinkable. A masterclass in restrained IPA brewing with floral and citrus hop character.',
    abv: 7.0,
    ibu: 60,
    iqScore: 93,
    flavorTags: ['Citrus', 'Floral', 'Clean', 'Balanced', 'Crisp'],
    foodPairings: ['Grilled salmon', 'Lobster roll', 'Fresh salad'],
    availability: 'Year-round',
  },
  {
    name: 'Dinner',
    slug: 'maine-beer-dinner',
    brewerySlug: 'maine-beer',
    style: 'Double IPA',
    description: 'The bigger sibling to Lunch. More hops, more complexity, but the same signature MBC balance and drinkability. A limited release worth seeking.',
    abv: 8.1,
    ibu: 85,
    iqScore: 95,
    flavorTags: ['Tropical', 'Pine', 'Complex', 'Balanced', 'Bold'],
    foodPairings: ['Grilled steak', 'Strong aged cheese', 'Herb-crusted lamb'],
    availability: 'Limited',
  },
  {
    name: 'Peeper',
    slug: 'maine-beer-peeper',
    brewerySlug: 'maine-beer',
    style: 'Pale Ale',
    description: 'A classic American pale ale with a lighter body and approachable hop character. Clean and refreshing with citrus and floral notes.',
    abv: 5.5,
    ibu: 40,
    iqScore: 85,
    flavorTags: ['Citrus', 'Floral', 'Light', 'Clean', 'Refreshing'],
    foodPairings: ['Grilled chicken', 'Light pasta', 'Fresh cheese'],
    availability: 'Year-round',
  },

  // Jester King (3 beers)
  {
    name: 'Le Petit Prince',
    slug: 'jester-king-le-petit-prince',
    brewerySlug: 'jester-king',
    style: 'Farmhouse Table Beer',
    description: 'A remarkable table beer at just 2.9% ABV with subtle farmhouse funk and incredible flavor depth. Proof that ABV and quality are unrelated.',
    abv: 2.9,
    ibu: 23,
    iqScore: 90,
    flavorTags: ['Farmhouse', 'Light', 'Crisp', 'Funky', 'Refreshing'],
    foodPairings: ['Grilled chicken', 'Fresh salad', 'Light cheese'],
    availability: 'Year-round',
  },
  {
    name: 'Atrial Rubicite',
    slug: 'jester-king-atrial-rubicite',
    brewerySlug: 'jester-king',
    style: 'Wild Ale',
    description: 'A refermented wild ale with raspberries. Vibrant fruit character meets complex mixed-culture fermentation for a truly special beer.',
    abv: 5.8,
    ibu: 10,
    iqScore: 95,
    flavorTags: ['Raspberry', 'Tart', 'Funky', 'Complex', 'Vibrant'],
    foodPairings: ['Dark chocolate', 'Aged cheese', 'Roasted duck'],
    availability: 'Limited',
  },
  {
    name: 'SPON',
    slug: 'jester-king-spon',
    brewerySlug: 'jester-king',
    style: 'Spontaneous Ale',
    description: 'A spontaneously fermented ale using a coolship to capture wild Texas Hill Country yeast. Tart, complex, and a true expression of terroir.',
    abv: 5.5,
    ibu: 10,
    iqScore: 92,
    flavorTags: ['Tart', 'Funky', 'Complex', 'Dry', 'Terroir'],
    foodPairings: ['Charcuterie', 'Aged gouda', 'Roasted chicken'],
    availability: 'Limited',
  },
];

async function main() {
  console.log('Populating breweries and beers...\n');

  // Phase 1: Upsert all breweries
  let breweryCount = 0;
  const breweryIdMap: Record<string, string> = {};

  for (const brewery of breweries) {
    const result = await prisma.brewery.upsert({
      where: { slug: brewery.slug },
      create: brewery,
      update: {},
    });
    breweryIdMap[brewery.slug] = result.id;
    breweryCount++;
    console.log(`  [${breweryCount}/${breweries.length}] Brewery: ${brewery.name} (${brewery.city}, ${brewery.state})`);
  }

  console.log(`\nCreated/updated ${breweryCount} breweries.\n`);

  // Phase 2: Upsert all beers
  let beerCount = 0;
  let beerSkipped = 0;

  for (const beer of beers) {
    const breweryId = breweryIdMap[beer.brewerySlug];
    if (!breweryId) {
      console.log(`  SKIP: Brewery not found for slug: ${beer.brewerySlug}`);
      beerSkipped++;
      continue;
    }

    const tier = getTier(beer.iqScore);

    await prisma.beer.upsert({
      where: { slug: beer.slug },
      create: {
        name: beer.name,
        slug: beer.slug,
        breweryId,
        style: beer.style,
        description: beer.description,
        abv: beer.abv,
        ibu: beer.ibu,
        iqScore: beer.iqScore,
        tier,
        flavorTags: beer.flavorTags,
        foodPairings: beer.foodPairings,
        availability: beer.availability,
      },
      update: {},
    });
    beerCount++;
    console.log(`  [${beerCount}/${beers.length}] Beer: ${beer.name} (${beer.style}, ${beer.abv}% ABV, IQ: ${beer.iqScore})`);
  }

  // Summary
  console.log('\n========================================');
  console.log('  BREWERY & BEER POPULATION COMPLETE');
  console.log('========================================\n');
  console.log(`Total breweries created/updated: ${breweryCount}`);
  console.log(`Total beers created/updated: ${beerCount}`);
  if (beerSkipped > 0) {
    console.log(`Beers skipped (missing brewery): ${beerSkipped}`);
  }

  // Breakdown by style
  const styleCounts: Record<string, number> = {};
  for (const beer of beers) {
    styleCounts[beer.style] = (styleCounts[beer.style] || 0) + 1;
  }
  console.log('\n--- Beers by Style ---');
  Object.entries(styleCounts)
    .sort((a, b) => b[1] - a[1])
    .forEach(([style, count]) => {
      console.log(`  ${style.padEnd(30)} ${count}`);
    });

  // Breakdown by state
  const stateCounts: Record<string, number> = {};
  for (const brewery of breweries) {
    stateCounts[brewery.state] = (stateCounts[brewery.state] || 0) + 1;
  }
  console.log('\n--- Breweries by State ---');
  Object.entries(stateCounts)
    .sort((a, b) => b[1] - a[1])
    .forEach(([state, count]) => {
      console.log(`  ${state.padEnd(5)} ${count}`);
    });
}

main()
  .catch((e) => {
    console.error('FATAL:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
