import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create achievements
  const achievements = [
    {
      name: 'First Sip',
      slug: 'first-sip',
      description: 'Write your first beer review',
      category: 'REVIEWING' as const,
      rarity: 'COMMON' as const,
      pointsAwarded: 10,
      criteria: { type: 'reviews_count', count: 1 },
    },
    {
      name: 'Beer Critic',
      slug: 'beer-critic',
      description: 'Write 10 beer reviews',
      category: 'REVIEWING' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 50,
      criteria: { type: 'reviews_count', count: 10 },
    },
    {
      name: 'Connoisseur',
      slug: 'connoisseur',
      description: 'Write 50 beer reviews',
      category: 'REVIEWING' as const,
      rarity: 'RARE' as const,
      pointsAwarded: 200,
      criteria: { type: 'reviews_count', count: 50 },
    },
    {
      name: 'Beer Sommelier',
      slug: 'beer-sommelier',
      description: 'Write 100 beer reviews',
      category: 'REVIEWING' as const,
      rarity: 'EPIC' as const,
      pointsAwarded: 500,
      criteria: { type: 'reviews_count', count: 100 },
    },
    {
      name: 'Scout',
      slug: 'scout',
      description: 'Report your first beer sighting',
      category: 'SIGHTING' as const,
      rarity: 'COMMON' as const,
      pointsAwarded: 10,
      criteria: { type: 'sightings_count', count: 1 },
    },
    {
      name: 'Beer Hunter',
      slug: 'beer-hunter',
      description: 'Report 25 beer sightings',
      category: 'SIGHTING' as const,
      rarity: 'RARE' as const,
      pointsAwarded: 150,
      criteria: { type: 'sightings_count', count: 25 },
    },
    {
      name: 'Scanner',
      slug: 'scanner',
      description: 'Scan your first beer',
      category: 'SCANNING' as const,
      rarity: 'COMMON' as const,
      pointsAwarded: 10,
      criteria: { type: 'scans_count', count: 1 },
    },
    {
      name: 'AI Enthusiast',
      slug: 'ai-enthusiast',
      description: 'Scan 50 beers',
      category: 'SCANNING' as const,
      rarity: 'RARE' as const,
      pointsAwarded: 150,
      criteria: { type: 'scans_count', count: 50 },
    },
    {
      name: 'Style Explorer',
      slug: 'style-explorer',
      description: 'Try 10 different beer styles',
      category: 'COLLECTION' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 75,
      criteria: { type: 'unique_styles', count: 10 },
    },
    {
      name: 'Brewery Hopper',
      slug: 'brewery-hopper',
      description: 'Review beers from 10 different breweries',
      category: 'COLLECTION' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 75,
      criteria: { type: 'unique_breweries', count: 10 },
    },
    {
      name: 'Influencer',
      slug: 'influencer',
      description: 'Gain 10 followers',
      category: 'SOCIAL' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 50,
      criteria: { type: 'followers_count', count: 10 },
    },
    {
      name: 'Beer Guru',
      slug: 'beer-guru',
      description: 'Gain 100 followers',
      category: 'SOCIAL' as const,
      rarity: 'EPIC' as const,
      pointsAwarded: 300,
      criteria: { type: 'followers_count', count: 100 },
    },
    {
      name: 'Helpful',
      slug: 'helpful',
      description: 'Receive 10 helpful votes on your reviews',
      category: 'SOCIAL' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 50,
      criteria: { type: 'helpful_votes', count: 10 },
    },
    {
      name: 'Level 5',
      slug: 'level-5',
      description: 'Reach level 5',
      category: 'SPECIAL' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 100,
      criteria: { type: 'level', count: 5 },
    },
    {
      name: 'Level 10',
      slug: 'level-10',
      description: 'Reach level 10',
      category: 'SPECIAL' as const,
      rarity: 'RARE' as const,
      pointsAwarded: 250,
      criteria: { type: 'level', count: 10 },
    },
    {
      name: 'Hop Head',
      slug: 'hop-head',
      description: 'Review 10 IPAs',
      category: 'COLLECTION' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 50,
      criteria: { type: 'style_count', style: 'IPA', count: 10 },
    },
    {
      name: 'Dark Side',
      slug: 'dark-side',
      description: 'Review 10 stouts or porters',
      category: 'COLLECTION' as const,
      rarity: 'UNCOMMON' as const,
      pointsAwarded: 50,
      criteria: { type: 'style_count', style: 'Stout', count: 10 },
    },
    {
      name: 'Sour Power',
      slug: 'sour-power',
      description: 'Review 5 sour beers',
      category: 'COLLECTION' as const,
      rarity: 'RARE' as const,
      pointsAwarded: 75,
      criteria: { type: 'style_count', style: 'Sour', count: 5 },
    },
  ];

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { slug: achievement.slug },
      create: achievement,
      update: achievement,
    });
  }

  console.log(`✅ Created ${achievements.length} achievements`);

  // Create comprehensive breweries
  const breweries = [
    // Classic American Craft
    {
      name: 'Sierra Nevada Brewing Co.',
      slug: 'sierra-nevada',
      type: 'REGIONAL' as const,
      description: 'One of America\'s most iconic craft breweries, founded in 1980. Known for pioneering the American Pale Ale style.',
      city: 'Chico',
      state: 'California',
      country: 'USA',
      specialties: ['Pale Ale', 'IPA', 'Stout'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1980,
      iqScore: 92,
    },
    {
      name: 'Bell\'s Brewery',
      slug: 'bells-brewery',
      type: 'REGIONAL' as const,
      description: 'Michigan craft brewing pioneer established in 1985. Home of the legendary Two Hearted Ale.',
      city: 'Kalamazoo',
      state: 'Michigan',
      country: 'USA',
      specialties: ['IPA', 'Stout', 'Wheat Beer'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1985,
      iqScore: 94,
    },
    {
      name: 'Stone Brewing',
      slug: 'stone-brewing',
      type: 'REGIONAL' as const,
      description: 'San Diego\'s craft beer giant known for bold, aggressive hop-forward beers since 1996.',
      city: 'Escondido',
      state: 'California',
      country: 'USA',
      specialties: ['IPA', 'Double IPA', 'Stout'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1996,
      iqScore: 88,
    },
    {
      name: 'Founders Brewing Co.',
      slug: 'founders-brewing',
      type: 'REGIONAL' as const,
      description: 'Grand Rapids brewing innovators famous for bold, complex beers like KBS and Breakfast Stout.',
      city: 'Grand Rapids',
      state: 'Michigan',
      country: 'USA',
      specialties: ['Stout', 'IPA', 'Red Ale'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1997,
      iqScore: 93,
    },
    {
      name: 'Dogfish Head Craft Brewery',
      slug: 'dogfish-head',
      type: 'REGIONAL' as const,
      description: 'Delaware innovators brewing off-centered ales for off-centered people since 1995.',
      city: 'Milton',
      state: 'Delaware',
      country: 'USA',
      specialties: ['IPA', 'Experimental', 'Fruit Beer'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1995,
      iqScore: 90,
    },
    // More Craft Powerhouses
    {
      name: 'Russian River Brewing Company',
      slug: 'russian-river',
      type: 'CRAFT' as const,
      description: 'Santa Rosa brewery famous for Pliny the Elder, consistently rated among the world\'s best IPAs.',
      city: 'Santa Rosa',
      state: 'California',
      country: 'USA',
      specialties: ['Double IPA', 'Sour', 'Belgian'],
      hasTaproom: true,
      hasTours: false,
      hasFood: true,
      foundedYear: 1997,
      iqScore: 97,
    },
    {
      name: 'Tree House Brewing Company',
      slug: 'tree-house',
      type: 'CRAFT' as const,
      description: 'Massachusetts brewery known for hazy New England IPAs that have achieved cult status.',
      city: 'Charlton',
      state: 'Massachusetts',
      country: 'USA',
      specialties: ['New England IPA', 'Stout', 'Pale Ale'],
      hasTaproom: true,
      hasTours: false,
      hasFood: false,
      foundedYear: 2011,
      iqScore: 96,
    },
    {
      name: 'The Alchemist',
      slug: 'the-alchemist',
      type: 'CRAFT' as const,
      description: 'Vermont brewery that started the hazy IPA craze with the legendary Heady Topper.',
      city: 'Stowe',
      state: 'Vermont',
      country: 'USA',
      specialties: ['Double IPA', 'IPA'],
      hasTaproom: true,
      hasTours: false,
      hasFood: false,
      foundedYear: 2003,
      iqScore: 95,
    },
    {
      name: 'Other Half Brewing Co.',
      slug: 'other-half',
      type: 'CRAFT' as const,
      description: 'Brooklyn brewery pushing the boundaries of hazy IPAs and imperial stouts.',
      city: 'Brooklyn',
      state: 'New York',
      country: 'USA',
      specialties: ['New England IPA', 'Imperial Stout', 'Sour'],
      hasTaproom: true,
      hasTours: false,
      hasFood: false,
      foundedYear: 2014,
      iqScore: 94,
    },
    {
      name: 'Trillium Brewing Company',
      slug: 'trillium',
      type: 'CRAFT' as const,
      description: 'Boston-area brewery known for exceptional IPAs, farmhouse ales, and wild ales.',
      city: 'Canton',
      state: 'Massachusetts',
      country: 'USA',
      specialties: ['New England IPA', 'Farmhouse Ale', 'Wild Ale'],
      hasTaproom: true,
      hasTours: false,
      hasFood: true,
      foundedYear: 2013,
      iqScore: 95,
    },
    // Sour & Belgian Specialists
    {
      name: 'Jester King Brewery',
      slug: 'jester-king',
      type: 'CRAFT' as const,
      description: 'Austin farmhouse brewery specializing in wild ales and spontaneous fermentation.',
      city: 'Austin',
      state: 'Texas',
      country: 'USA',
      specialties: ['Farmhouse Ale', 'Wild Ale', 'Sour'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      dogFriendly: true,
      foundedYear: 2010,
      iqScore: 93,
    },
    {
      name: 'Cascade Brewing',
      slug: 'cascade-brewing',
      type: 'CRAFT' as const,
      description: 'Portland\'s House of Sour, pioneering American sour ales since 1998.',
      city: 'Portland',
      state: 'Oregon',
      country: 'USA',
      specialties: ['Sour', 'Fruit Beer', 'Barrel-Aged'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1998,
      iqScore: 91,
    },
    // Stout Masters
    {
      name: 'Toppling Goliath Brewing Co.',
      slug: 'toppling-goliath',
      type: 'CRAFT' as const,
      description: 'Iowa brewery known for world-class IPAs and imperial stouts, including the legendary Kentucky Brunch.',
      city: 'Decorah',
      state: 'Iowa',
      country: 'USA',
      specialties: ['Double IPA', 'Imperial Stout', 'Barrel-Aged'],
      hasTaproom: true,
      hasTours: false,
      hasFood: false,
      foundedYear: 2009,
      iqScore: 96,
    },
    {
      name: 'Cigar City Brewing',
      slug: 'cigar-city',
      type: 'REGIONAL' as const,
      description: 'Tampa brewery famous for Jai Alai IPA and Hunahpu\'s Imperial Stout.',
      city: 'Tampa',
      state: 'Florida',
      country: 'USA',
      specialties: ['IPA', 'Imperial Stout', 'Lager'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 2009,
      iqScore: 91,
    },
    // West Coast Legends
    {
      name: 'Firestone Walker Brewing Company',
      slug: 'firestone-walker',
      type: 'REGIONAL' as const,
      description: 'Paso Robles brewery mastering both hop-forward and barrel-aged styles.',
      city: 'Paso Robles',
      state: 'California',
      country: 'USA',
      specialties: ['IPA', 'Pale Ale', 'Barrel-Aged'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1996,
      iqScore: 92,
    },
    {
      name: 'Modern Times Beer',
      slug: 'modern-times',
      type: 'CRAFT' as const,
      description: 'San Diego\'s employee-owned brewery known for creative IPAs and coffee beers.',
      city: 'San Diego',
      state: 'California',
      country: 'USA',
      specialties: ['IPA', 'Stout', 'Coffee Beer'],
      hasTaproom: true,
      hasTours: false,
      hasFood: true,
      foundedYear: 2013,
      iqScore: 89,
    },
    {
      name: 'Deschutes Brewery',
      slug: 'deschutes',
      type: 'REGIONAL' as const,
      description: 'Oregon\'s family-owned brewery crafting beloved beers like Black Butte Porter since 1988.',
      city: 'Bend',
      state: 'Oregon',
      country: 'USA',
      specialties: ['Porter', 'IPA', 'Pale Ale'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1988,
      iqScore: 90,
    },
    // East Coast Favorites
    {
      name: 'Maine Beer Company',
      slug: 'maine-beer',
      type: 'CRAFT' as const,
      description: 'Freeport brewery focused on sustainability and exceptional hop-forward ales.',
      city: 'Freeport',
      state: 'Maine',
      country: 'USA',
      specialties: ['Pale Ale', 'IPA', 'Double IPA'],
      hasTaproom: true,
      hasTours: true,
      hasFood: false,
      foundedYear: 2009,
      iqScore: 93,
    },
    {
      name: 'Hill Farmstead Brewery',
      slug: 'hill-farmstead',
      type: 'CRAFT' as const,
      description: 'Vermont farmhouse brewery consistently rated among the best in the world.',
      city: 'Greensboro',
      state: 'Vermont',
      country: 'USA',
      specialties: ['Farmhouse Ale', 'IPA', 'Saison'],
      hasTaproom: true,
      hasTours: false,
      hasFood: false,
      foundedYear: 2010,
      iqScore: 98,
    },
    // Midwest Gems
    {
      name: '3 Floyds Brewing Co.',
      slug: '3-floyds',
      type: 'CRAFT' as const,
      description: 'Indiana brewery with cult following, home of Zombie Dust and Dark Lord.',
      city: 'Munster',
      state: 'Indiana',
      country: 'USA',
      specialties: ['Pale Ale', 'Imperial Stout', 'IPA'],
      hasTaproom: true,
      hasTours: false,
      hasFood: true,
      foundedYear: 1996,
      iqScore: 94,
    },
    {
      name: 'Revolution Brewing',
      slug: 'revolution-brewing',
      type: 'REGIONAL' as const,
      description: 'Chicago\'s largest independently owned brewery known for Anti-Hero IPA.',
      city: 'Chicago',
      state: 'Illinois',
      country: 'USA',
      specialties: ['IPA', 'Lager', 'Barrel-Aged'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 2010,
      iqScore: 89,
    },
    {
      name: 'Surly Brewing Co.',
      slug: 'surly',
      type: 'REGIONAL' as const,
      description: 'Minneapolis brewery that changed Minnesota law to allow taprooms.',
      city: 'Minneapolis',
      state: 'Minnesota',
      country: 'USA',
      specialties: ['IPA', 'Stout', 'Pilsner'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 2006,
      iqScore: 90,
    },
    // International Influences
    {
      name: 'Weihenstephaner',
      slug: 'weihenstephaner',
      type: 'MAJOR' as const,
      description: 'The world\'s oldest brewery, operating since 1040 in Bavaria, Germany.',
      city: 'Freising',
      state: 'Bavaria',
      country: 'Germany',
      specialties: ['Hefeweizen', 'Pilsner', 'Dunkel'],
      hasTaproom: true,
      hasTours: true,
      hasFood: true,
      foundedYear: 1040,
      iqScore: 95,
    },
    {
      name: 'Cantillon Brewery',
      slug: 'cantillon',
      type: 'CRAFT' as const,
      description: 'Brussels lambic brewery producing traditional spontaneous fermentation beers since 1900.',
      city: 'Brussels',
      country: 'Belgium',
      specialties: ['Lambic', 'Gueuze', 'Kriek'],
      hasTaproom: true,
      hasTours: true,
      hasFood: false,
      foundedYear: 1900,
      iqScore: 99,
    },
  ];

  for (const brewery of breweries) {
    await prisma.brewery.upsert({
      where: { slug: brewery.slug },
      create: brewery,
      update: brewery,
    });
  }

  console.log(`✅ Created ${breweries.length} breweries`);

  // Get all brewery IDs
  const breweryMap: Record<string, string> = {};
  for (const b of breweries) {
    const brewery = await prisma.brewery.findUnique({ where: { slug: b.slug } });
    if (brewery) breweryMap[b.slug] = brewery.id;
  }

  // Create comprehensive beer database
  const beers = [
    // Sierra Nevada
    {
      name: 'Pale Ale',
      slug: 'sierra-nevada-pale-ale',
      breweryId: breweryMap['sierra-nevada'],
      style: 'American Pale Ale',
      description: 'The one that started it all. Full-flavored with a smooth finish. Deep amber color with piney, citrus hop aromas.',
      abv: 5.6,
      ibu: 38,
      iqScore: 88,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'piney', 'balanced', 'caramel'],
      foodPairings: ['burgers', 'pizza', 'grilled chicken', 'cheddar cheese'],
    },
    {
      name: 'Torpedo Extra IPA',
      slug: 'sierra-nevada-torpedo',
      breweryId: breweryMap['sierra-nevada'],
      style: 'American IPA',
      description: 'An assertive, hop-heavy American IPA with a dry-hopped intensity using the hop torpedo.',
      abv: 7.2,
      ibu: 65,
      iqScore: 86,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'resinous', 'tropical', 'bitter'],
      foodPairings: ['spicy wings', 'Thai curry', 'blue cheese'],
    },
    {
      name: 'Hazy Little Thing',
      slug: 'sierra-nevada-hazy-little-thing',
      breweryId: breweryMap['sierra-nevada'],
      style: 'New England IPA',
      description: 'Unfiltered, unprocessed, simple, and hazy. Bursting with citrus and tropical aromas.',
      abv: 6.7,
      ibu: 35,
      iqScore: 84,
      tier: 'GOLD' as const,
      flavorTags: ['hazy', 'juicy', 'tropical', 'citrus', 'smooth'],
      foodPairings: ['fish tacos', 'ceviche', 'goat cheese salad'],
    },

    // Bell's
    {
      name: 'Two Hearted Ale',
      slug: 'bells-two-hearted-ale',
      breweryId: breweryMap['bells-brewery'],
      style: 'American IPA',
      description: 'Brewed with 100% Centennial hops. Perfectly balanced with a malt backbone and intense hop aroma.',
      abv: 7.0,
      ibu: 55,
      iqScore: 96,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'grapefruit', 'floral', 'piney'],
      foodPairings: ['spicy tacos', 'curry', 'blue cheese', 'grilled salmon'],
    },
    {
      name: 'Oberon Ale',
      slug: 'bells-oberon',
      breweryId: breweryMap['bells-brewery'],
      style: 'American Wheat Ale',
      description: 'A wheat ale fermented with Bell\'s house yeast, mixing a spicy hop character with mildly fruity aromas.',
      abv: 5.8,
      ibu: 15,
      iqScore: 85,
      tier: 'PLATINUM' as const,
      flavorTags: ['wheat', 'citrus', 'spicy', 'refreshing', 'light'],
      foodPairings: ['summer salads', 'grilled seafood', 'light pasta'],
    },
    {
      name: 'Hopslam Ale',
      slug: 'bells-hopslam',
      breweryId: breweryMap['bells-brewery'],
      style: 'Double IPA',
      description: 'A bolder imperial IPA with six hop varietals and honey. A cult favorite released annually.',
      abv: 10.0,
      ibu: 70,
      iqScore: 94,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'honey', 'citrus', 'strong', 'complex'],
      foodPairings: ['spicy BBQ', 'aged gouda', 'carrot cake'],
    },

    // Stone
    {
      name: 'Arrogant Bastard Ale',
      slug: 'stone-arrogant-bastard',
      breweryId: breweryMap['stone-brewing'],
      style: 'American Strong Ale',
      description: 'This is an aggressive ale. You probably won\'t like it.',
      abv: 7.2,
      ibu: 100,
      iqScore: 85,
      tier: 'GOLD' as const,
      flavorTags: ['bitter', 'malty', 'aggressive', 'bold', 'caramel'],
      foodPairings: ['steak', 'barbecue', 'sharp cheddar', 'dark chocolate'],
    },
    {
      name: 'Stone IPA',
      slug: 'stone-ipa',
      breweryId: breweryMap['stone-brewing'],
      style: 'American IPA',
      description: 'The iconic West Coast IPA with a crisp, clean finish and aggressive hop character.',
      abv: 6.9,
      ibu: 71,
      iqScore: 87,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'piney', 'crisp', 'bitter'],
      foodPairings: ['buffalo wings', 'fish and chips', 'jalapeño poppers'],
    },
    {
      name: 'Delicious IPA',
      slug: 'stone-delicious-ipa',
      breweryId: breweryMap['stone-brewing'],
      style: 'American IPA',
      description: 'Powerfully hoppy, citrusy and tropical with lemondrop and El Dorado hops.',
      abv: 7.7,
      ibu: 75,
      iqScore: 86,
      tier: 'PLATINUM' as const,
      flavorTags: ['tropical', 'citrus', 'lemon', 'hoppy', 'juicy'],
      foodPairings: ['grilled shrimp', 'mango salsa', 'key lime pie'],
    },

    // Founders
    {
      name: 'Breakfast Stout',
      slug: 'founders-breakfast-stout',
      breweryId: breweryMap['founders-brewing'],
      style: 'Imperial Stout',
      description: 'Double chocolate, coffee, and oatmeal stout brewed with flaked oats, Sumatra and Kona coffee.',
      abv: 8.3,
      ibu: 60,
      iqScore: 94,
      tier: 'DIAMOND' as const,
      flavorTags: ['coffee', 'chocolate', 'roasted', 'creamy', 'oatmeal'],
      foodPairings: ['chocolate desserts', 'pancakes', 'smoked meats', 'vanilla ice cream'],
    },
    {
      name: 'KBS (Kentucky Breakfast Stout)',
      slug: 'founders-kbs',
      breweryId: breweryMap['founders-brewing'],
      style: 'Imperial Stout',
      description: 'Barrel-aged Breakfast Stout. Cave-aged in bourbon barrels for one year.',
      abv: 12.3,
      ibu: 70,
      iqScore: 98,
      tier: 'DIAMOND' as const,
      flavorTags: ['bourbon', 'coffee', 'chocolate', 'vanilla', 'oak'],
      foodPairings: ['beef short ribs', 'flourless chocolate cake', 'aged cheddar'],
    },
    {
      name: 'All Day IPA',
      slug: 'founders-all-day-ipa',
      breweryId: breweryMap['founders-brewing'],
      style: 'Session IPA',
      description: 'The perfect balance of hops and malt in a sessionable package.',
      abv: 4.7,
      ibu: 42,
      iqScore: 82,
      tier: 'GOLD' as const,
      flavorTags: ['hoppy', 'sessionable', 'citrus', 'light', 'crisp'],
      foodPairings: ['fish tacos', 'garden salad', 'popcorn'],
    },
    {
      name: 'Dirty Bastard',
      slug: 'founders-dirty-bastard',
      breweryId: breweryMap['founders-brewing'],
      style: 'Scotch Ale',
      description: 'Scotch ale brewed with peated malt for a subtle smokiness.',
      abv: 8.5,
      ibu: 50,
      iqScore: 87,
      tier: 'PLATINUM' as const,
      flavorTags: ['malty', 'smoky', 'caramel', 'toffee', 'rich'],
      foodPairings: ['lamb', 'haggis', 'smoked salmon', 'butterscotch'],
    },

    // Dogfish Head
    {
      name: '60 Minute IPA',
      slug: 'dogfish-head-60-minute-ipa',
      breweryId: breweryMap['dogfish-head'],
      style: 'American IPA',
      description: 'Continually hopped for 60 minutes for a beautifully balanced, exceptionally drinkable IPA.',
      abv: 6.0,
      ibu: 60,
      iqScore: 87,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'balanced', 'smooth', 'piney'],
      foodPairings: ['fish tacos', 'pad thai', 'goat cheese', 'carrot cake'],
    },
    {
      name: '90 Minute IPA',
      slug: 'dogfish-head-90-minute-ipa',
      breweryId: breweryMap['dogfish-head'],
      style: 'Imperial IPA',
      description: 'Continually hopped for 90 minutes. A beautifully complex imperial IPA.',
      abv: 9.0,
      ibu: 90,
      iqScore: 91,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'malty', 'complex', 'warming'],
      foodPairings: ['aged steak', 'stilton cheese', 'bread pudding'],
    },
    {
      name: 'SeaQuench Ale',
      slug: 'dogfish-head-seaquench',
      breweryId: breweryMap['dogfish-head'],
      style: 'Sour/Gose',
      description: 'Session sour quencher with black limes, sour lime juice, and sea salt.',
      abv: 4.9,
      ibu: 10,
      iqScore: 84,
      tier: 'GOLD' as const,
      flavorTags: ['sour', 'salty', 'lime', 'refreshing', 'tart'],
      foodPairings: ['ceviche', 'oysters', 'fish and chips', 'summer salads'],
    },

    // Russian River
    {
      name: 'Pliny the Elder',
      slug: 'russian-river-pliny-the-elder',
      breweryId: breweryMap['russian-river'],
      style: 'Double IPA',
      description: 'The benchmark American Double IPA. Well-balanced with a nice malt backbone.',
      abv: 8.0,
      ibu: 100,
      iqScore: 99,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'floral', 'balanced', 'resinous'],
      foodPairings: ['spicy Thai', 'aged gouda', 'grilled lamb', 'mango desserts'],
    },
    {
      name: 'Pliny the Younger',
      slug: 'russian-river-pliny-the-younger',
      breweryId: breweryMap['russian-river'],
      style: 'Triple IPA',
      description: 'The most sought-after beer in America. Released once per year.',
      abv: 10.25,
      ibu: 100,
      iqScore: 100,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'tropical', 'smooth', 'complex'],
      foodPairings: ['spicy foods', 'aged cheeses', 'white chocolate'],
    },
    {
      name: 'Supplication',
      slug: 'russian-river-supplication',
      breweryId: breweryMap['russian-river'],
      style: 'American Wild Ale',
      description: 'Brown ale aged in Pinot Noir barrels with sour cherries, Brettanomyces, and Lactobacillus.',
      abv: 7.0,
      ibu: 10,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['sour', 'cherry', 'wine', 'funky', 'complex'],
      foodPairings: ['duck confit', 'brie', 'dark chocolate', 'foie gras'],
    },

    // Tree House
    {
      name: 'Julius',
      slug: 'tree-house-julius',
      breweryId: breweryMap['tree-house'],
      style: 'New England IPA',
      description: 'Complex, brooding, and incredibly enjoyable. Notes of passion fruit, mango, and citrus.',
      abv: 6.8,
      ibu: 60,
      iqScore: 97,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'tropical', 'juicy', 'smooth', 'creamy'],
      foodPairings: ['grilled shrimp', 'mango salsa', 'soft cheeses'],
    },
    {
      name: 'Green',
      slug: 'tree-house-green',
      breweryId: breweryMap['tree-house'],
      style: 'New England IPA',
      description: 'Bright, aromatic, and bursting with notes of honeydew and citrus.',
      abv: 7.5,
      ibu: 70,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'citrus', 'honeydew', 'tropical', 'soft'],
      foodPairings: ['crab cakes', 'citrus salads', 'goat cheese'],
    },
    {
      name: 'Very Green',
      slug: 'tree-house-very-green',
      breweryId: breweryMap['tree-house'],
      style: 'Double IPA',
      description: 'Double IPA version of Green with amplified hop character.',
      abv: 8.3,
      ibu: 80,
      iqScore: 96,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'intense', 'tropical', 'creamy', 'bold'],
      foodPairings: ['lobster', 'aged cheddar', 'key lime desserts'],
    },

    // The Alchemist
    {
      name: 'Heady Topper',
      slug: 'alchemist-heady-topper',
      breweryId: breweryMap['the-alchemist'],
      style: 'Double IPA',
      description: 'The original hazy IPA that started a revolution. Drink from the can.',
      abv: 8.0,
      ibu: 100,
      iqScore: 98,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'citrus', 'tropical', 'dank', 'piney'],
      foodPairings: ['spicy wings', 'curry', 'strong cheeses'],
    },
    {
      name: 'Focal Banger',
      slug: 'alchemist-focal-banger',
      breweryId: breweryMap['the-alchemist'],
      style: 'American IPA',
      description: 'Single IPA brewed to amplify the juicy, tropical flavors of hops.',
      abv: 7.0,
      ibu: 60,
      iqScore: 94,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'tropical', 'mango', 'papaya', 'smooth'],
      foodPairings: ['fish tacos', 'coconut shrimp', 'tropical fruit'],
    },

    // Other Half
    {
      name: 'Green City',
      slug: 'other-half-green-city',
      breweryId: breweryMap['other-half'],
      style: 'New England IPA',
      description: 'Flagship hazy IPA bursting with tropical fruit and citrus notes.',
      abv: 7.0,
      ibu: 45,
      iqScore: 92,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'juicy', 'tropical', 'citrus', 'soft'],
      foodPairings: ['ceviche', 'grilled fish', 'citrus salads'],
    },
    {
      name: 'DDH All Citra Everything',
      slug: 'other-half-ddh-all-citra-everything',
      breweryId: breweryMap['other-half'],
      style: 'Double IPA',
      description: 'Double dry-hopped with Citra hops for maximum citrus intensity.',
      abv: 8.5,
      ibu: 60,
      iqScore: 94,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'citrus', 'grapefruit', 'tropical', 'intense'],
      foodPairings: ['spicy Thai', 'citrus desserts', 'sharp cheeses'],
    },

    // Trillium
    {
      name: 'Congress Street',
      slug: 'trillium-congress-street',
      breweryId: breweryMap['trillium'],
      style: 'New England IPA',
      description: 'Year-round hazy IPA with notes of tangerine, mango, and pineapple.',
      abv: 7.2,
      ibu: 50,
      iqScore: 93,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'tropical', 'citrus', 'smooth', 'balanced'],
      foodPairings: ['lobster rolls', 'grilled shrimp', 'fresh fruit'],
    },
    {
      name: 'DDH Fort Point',
      slug: 'trillium-ddh-fort-point',
      breweryId: breweryMap['trillium'],
      style: 'American Pale Ale',
      description: 'Double dry-hopped pale ale with bright citrus and stone fruit character.',
      abv: 6.6,
      ibu: 40,
      iqScore: 91,
      tier: 'DIAMOND' as const,
      flavorTags: ['hazy', 'citrus', 'peach', 'soft', 'refreshing'],
      foodPairings: ['fish tacos', 'summer salads', 'goat cheese'],
    },

    // Jester King
    {
      name: 'Le Petit Prince',
      slug: 'jester-king-le-petit-prince',
      breweryId: breweryMap['jester-king'],
      style: 'Farmhouse Ale/Table Beer',
      description: 'Light, refreshing farmhouse table beer with subtle funk.',
      abv: 2.9,
      ibu: 20,
      iqScore: 88,
      tier: 'PLATINUM' as const,
      flavorTags: ['farmhouse', 'light', 'refreshing', 'subtle', 'crisp'],
      foodPairings: ['salads', 'light seafood', 'picnic fare'],
    },
    {
      name: 'Atrial Rubicite',
      slug: 'jester-king-atrial-rubicite',
      breweryId: breweryMap['jester-king'],
      style: 'Fruited Sour/Wild Ale',
      description: 'Sour ale refermented with raspberries. Tart, fruity, and complex.',
      abv: 5.8,
      ibu: 10,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['sour', 'raspberry', 'tart', 'complex', 'funky'],
      foodPairings: ['duck', 'brie', 'raspberry desserts', 'pork'],
    },

    // Toppling Goliath
    {
      name: 'King Sue',
      slug: 'toppling-goliath-king-sue',
      breweryId: breweryMap['toppling-goliath'],
      style: 'Double IPA',
      description: 'Double IPA brewed with Citra hops for massive tropical fruit character.',
      abv: 7.8,
      ibu: 85,
      iqScore: 96,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'tropical', 'mango', 'citrus', 'juicy'],
      foodPairings: ['spicy Thai', 'mango salsa', 'aged gouda'],
    },
    {
      name: 'PseudoSue',
      slug: 'toppling-goliath-pseudosue',
      breweryId: breweryMap['toppling-goliath'],
      style: 'American Pale Ale',
      description: 'Flagship pale ale with Citra hops. Incredibly smooth and drinkable.',
      abv: 5.8,
      ibu: 50,
      iqScore: 93,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'tropical', 'smooth', 'balanced'],
      foodPairings: ['fish tacos', 'grilled chicken', 'summer salads'],
    },

    // Cigar City
    {
      name: 'Jai Alai IPA',
      slug: 'cigar-city-jai-alai',
      breweryId: breweryMap['cigar-city'],
      style: 'American IPA',
      description: 'Bold, citrus-forward IPA named after the Cuban sport. A Florida classic.',
      abv: 7.5,
      ibu: 70,
      iqScore: 90,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'tropical', 'bold', 'crisp'],
      foodPairings: ['Cuban sandwich', 'spicy tacos', 'key lime pie'],
    },
    {
      name: 'Hunahpu\'s Imperial Stout',
      slug: 'cigar-city-hunahpus',
      breweryId: breweryMap['cigar-city'],
      style: 'Imperial Stout',
      description: 'Imperial stout aged on cocoa nibs, cinnamon, and ancho and pasilla chiles.',
      abv: 11.0,
      ibu: 45,
      iqScore: 97,
      tier: 'DIAMOND' as const,
      flavorTags: ['chocolate', 'spicy', 'cinnamon', 'complex', 'rich'],
      foodPairings: ['mole', 'dark chocolate', 'smoked meats'],
    },

    // Firestone Walker
    {
      name: 'Union Jack IPA',
      slug: 'firestone-walker-union-jack',
      breweryId: breweryMap['firestone-walker'],
      style: 'American IPA',
      description: 'West Coast IPA with a perfect balance of hoppy aggression and drinkability.',
      abv: 7.0,
      ibu: 70,
      iqScore: 89,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'piney', 'crisp', 'dry'],
      foodPairings: ['fish and chips', 'spicy wings', 'aged cheddar'],
    },
    {
      name: 'Parabola',
      slug: 'firestone-walker-parabola',
      breweryId: breweryMap['firestone-walker'],
      style: 'Russian Imperial Stout',
      description: 'Barrel-aged imperial stout with notes of vanilla, chocolate, and bourbon.',
      abv: 14.0,
      ibu: 75,
      iqScore: 97,
      tier: 'DIAMOND' as const,
      flavorTags: ['bourbon', 'chocolate', 'vanilla', 'oak', 'complex'],
      foodPairings: ['beef short ribs', 'crème brûlée', 'dark chocolate truffles'],
    },

    // Deschutes
    {
      name: 'Black Butte Porter',
      slug: 'deschutes-black-butte-porter',
      breweryId: breweryMap['deschutes'],
      style: 'American Porter',
      description: 'Creamy, chocolatey porter with subtle hop bitterness. Oregon\'s favorite porter.',
      abv: 5.5,
      ibu: 30,
      iqScore: 87,
      tier: 'PLATINUM' as const,
      flavorTags: ['chocolate', 'coffee', 'creamy', 'roasted', 'smooth'],
      foodPairings: ['smoked ribs', 'chocolate cake', 'grilled portobello'],
    },
    {
      name: 'Fresh Squeezed IPA',
      slug: 'deschutes-fresh-squeezed',
      breweryId: breweryMap['deschutes'],
      style: 'American IPA',
      description: 'Citrus-forward IPA bursting with Citra and Mosaic hops.',
      abv: 6.4,
      ibu: 60,
      iqScore: 86,
      tier: 'PLATINUM' as const,
      flavorTags: ['citrus', 'grapefruit', 'hoppy', 'juicy', 'refreshing'],
      foodPairings: ['fish tacos', 'citrus salads', 'goat cheese'],
    },

    // Maine Beer Company
    {
      name: 'Lunch',
      slug: 'maine-beer-lunch',
      breweryId: breweryMap['maine-beer'],
      style: 'American IPA',
      description: 'Balanced yet hop-forward IPA. Citrusy, floral, and endlessly drinkable.',
      abv: 7.0,
      ibu: 65,
      iqScore: 93,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'floral', 'balanced', 'clean'],
      foodPairings: ['lobster rolls', 'grilled fish', 'fresh salads'],
    },
    {
      name: 'Dinner',
      slug: 'maine-beer-dinner',
      breweryId: breweryMap['maine-beer'],
      style: 'Double IPA',
      description: 'Double IPA successor to Lunch. More hops, more complexity.',
      abv: 8.2,
      ibu: 75,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'tropical', 'piney', 'complex', 'bold'],
      foodPairings: ['steak', 'aged cheeses', 'rich desserts'],
    },

    // Hill Farmstead
    {
      name: 'Edward',
      slug: 'hill-farmstead-edward',
      breweryId: breweryMap['hill-farmstead'],
      style: 'American Pale Ale',
      description: 'Named after grandfather. Endlessly balanced, hoppy American pale ale.',
      abv: 5.2,
      ibu: 45,
      iqScore: 96,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'floral', 'clean', 'crisp'],
      foodPairings: ['grilled chicken', 'light salads', 'mild cheeses'],
    },
    {
      name: 'Abner',
      slug: 'hill-farmstead-abner',
      breweryId: breweryMap['hill-farmstead'],
      style: 'Double IPA',
      description: 'Named after great-grandfather. Exceptional balance for a double IPA.',
      abv: 8.0,
      ibu: 100,
      iqScore: 98,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'piney', 'balanced', 'refined'],
      foodPairings: ['roast pork', 'aged gouda', 'spiced apple desserts'],
    },
    {
      name: 'Ann',
      slug: 'hill-farmstead-ann',
      breweryId: breweryMap['hill-farmstead'],
      style: 'Saison',
      description: 'Named after grandmother. Dry, effervescent farmhouse ale.',
      abv: 6.0,
      ibu: 20,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['farmhouse', 'spicy', 'dry', 'effervescent', 'complex'],
      foodPairings: ['roast chicken', 'mussels', 'goat cheese', 'fresh fruit'],
    },

    // 3 Floyds
    {
      name: 'Zombie Dust',
      slug: '3-floyds-zombie-dust',
      breweryId: breweryMap['3-floyds'],
      style: 'American Pale Ale',
      description: 'Intensely hopped pale ale with Citra hops. A cult classic.',
      abv: 6.2,
      ibu: 50,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['hoppy', 'citrus', 'tropical', 'juicy', 'bold'],
      foodPairings: ['spicy wings', 'tacos', 'aged cheddar'],
    },
    {
      name: 'Dark Lord',
      slug: '3-floyds-dark-lord',
      breweryId: breweryMap['3-floyds'],
      style: 'Russian Imperial Stout',
      description: 'Legendary imperial stout released on Dark Lord Day annually.',
      abv: 15.0,
      ibu: 75,
      iqScore: 97,
      tier: 'DIAMOND' as const,
      flavorTags: ['chocolate', 'coffee', 'molasses', 'dark fruit', 'intense'],
      foodPairings: ['braised short ribs', 'chocolate torte', 'aged stilton'],
    },

    // Revolution
    {
      name: 'Anti-Hero IPA',
      slug: 'revolution-anti-hero',
      breweryId: breweryMap['revolution-brewing'],
      style: 'American IPA',
      description: 'Chicago\'s most popular IPA. Boldly citrus with a clean finish.',
      abv: 6.5,
      ibu: 65,
      iqScore: 86,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'grapefruit', 'piney', 'balanced'],
      foodPairings: ['Chicago deep dish', 'wings', 'aged cheddar'],
    },

    // Surly
    {
      name: 'Furious',
      slug: 'surly-furious',
      breweryId: breweryMap['surly'],
      style: 'American IPA',
      description: 'Aggressively hopped American IPA that helped change Minnesota law.',
      abv: 6.6,
      ibu: 99,
      iqScore: 88,
      tier: 'PLATINUM' as const,
      flavorTags: ['hoppy', 'citrus', 'piney', 'aggressive', 'bold'],
      foodPairings: ['spicy foods', 'aged cheeses', 'grilled meats'],
    },
    {
      name: 'Darkness',
      slug: 'surly-darkness',
      breweryId: breweryMap['surly'],
      style: 'Russian Imperial Stout',
      description: 'Annual release imperial stout. Rich, decadent, and sought-after.',
      abv: 12.0,
      ibu: 100,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['chocolate', 'coffee', 'dark fruit', 'complex', 'warming'],
      foodPairings: ['chocolate desserts', 'smoked brisket', 'blue cheese'],
    },

    // Weihenstephaner
    {
      name: 'Hefeweissbier',
      slug: 'weihenstephaner-hefeweissbier',
      breweryId: breweryMap['weihenstephaner'],
      style: 'Hefeweizen',
      description: 'The benchmark Bavarian hefeweizen. Banana, clove, and wheat perfection.',
      abv: 5.4,
      ibu: 14,
      iqScore: 95,
      tier: 'DIAMOND' as const,
      flavorTags: ['wheat', 'banana', 'clove', 'refreshing', 'cloudy'],
      foodPairings: ['weisswurst', 'pretzels', 'light salads', 'fruit tarts'],
    },
    {
      name: 'Vitus',
      slug: 'weihenstephaner-vitus',
      breweryId: breweryMap['weihenstephaner'],
      style: 'Weizenbock',
      description: 'Strong wheat beer with notes of banana, vanilla, and clove.',
      abv: 7.7,
      ibu: 17,
      iqScore: 93,
      tier: 'DIAMOND' as const,
      flavorTags: ['wheat', 'banana', 'vanilla', 'clove', 'warming'],
      foodPairings: ['roast pork', 'apple strudel', 'aged gouda'],
    },

    // Cantillon
    {
      name: 'Gueuze 100% Lambic',
      slug: 'cantillon-gueuze',
      breweryId: breweryMap['cantillon'],
      style: 'Gueuze',
      description: 'Blend of 1, 2, and 3 year old lambics. Tart, funky, and complex.',
      abv: 5.0,
      ibu: 0,
      iqScore: 99,
      tier: 'DIAMOND' as const,
      flavorTags: ['sour', 'funky', 'complex', 'tart', 'dry'],
      foodPairings: ['mussels', 'aged cheeses', 'pâté', 'oysters'],
    },
    {
      name: 'Rosé de Gambrinus',
      slug: 'cantillon-rose-de-gambrinus',
      breweryId: breweryMap['cantillon'],
      style: 'Fruited Lambic',
      description: 'Lambic fermented with raspberries. Elegantly tart and fruity.',
      abv: 5.0,
      ibu: 0,
      iqScore: 98,
      tier: 'DIAMOND' as const,
      flavorTags: ['sour', 'raspberry', 'tart', 'funky', 'elegant'],
      foodPairings: ['duck', 'goat cheese', 'raspberry desserts', 'dark chocolate'],
    },
    {
      name: 'Kriek 100% Lambic',
      slug: 'cantillon-kriek',
      breweryId: breweryMap['cantillon'],
      style: 'Kriek/Cherry Lambic',
      description: 'Traditional kriek made with whole sour cherries. Bone dry and complex.',
      abv: 5.0,
      ibu: 0,
      iqScore: 98,
      tier: 'DIAMOND' as const,
      flavorTags: ['sour', 'cherry', 'tart', 'funky', 'dry'],
      foodPairings: ['duck confit', 'brie', 'cherry desserts', 'game meats'],
    },
  ];

  for (const beer of beers) {
    if (!beer.breweryId) continue;
    await prisma.beer.upsert({
      where: { slug: beer.slug },
      create: beer,
      update: beer,
    });
  }

  console.log(`✅ Created ${beers.length} beers`);

  // Create demo users
  const passwordHash = await bcrypt.hash('Demo123!', 12);

  const demoUsers = [
    {
      email: 'demo@brewiq.ai',
      username: 'demo',
      displayName: 'Demo User',
      bio: 'Beer enthusiast and craft explorer. Always hunting for the next great pour.',
      passwordHash,
      isVerified: true,
      membershipTier: 'PRO' as const,
      points: 1250,
      level: 8,
    },
    {
      email: 'hophead@brewiq.ai',
      username: 'hophead',
      displayName: 'Hop Head Hannah',
      bio: 'IPA fanatic. The hazier, the better. 🍺',
      passwordHash,
      isVerified: true,
      membershipTier: 'UNLIMITED' as const,
      points: 3500,
      level: 15,
    },
    {
      email: 'stoutlover@brewiq.ai',
      username: 'stoutlover',
      displayName: 'Stout Steve',
      bio: 'Dark beer devotee. Imperial stouts are my spirit animal.',
      passwordHash,
      isVerified: true,
      membershipTier: 'PRO' as const,
      points: 2100,
      level: 11,
    },
    {
      email: 'sourpusher@brewiq.ai',
      username: 'sourpusher',
      displayName: 'Sour Sarah',
      bio: 'Wild ales, lambics, and all things funky. Pucker up!',
      passwordHash,
      isVerified: true,
      membershipTier: 'PRO' as const,
      points: 1800,
      level: 10,
    },
    {
      email: 'craftcurious@brewiq.ai',
      username: 'craftcurious',
      displayName: 'Craft Curious Chris',
      bio: 'New to craft beer and loving every sip. Recommendations welcome!',
      passwordHash,
      isVerified: true,
      membershipTier: 'FREE' as const,
      points: 350,
      level: 3,
    },
  ];

  for (const user of demoUsers) {
    await prisma.user.upsert({
      where: { email: user.email },
      create: user,
      update: {},
    });
  }

  console.log(`✅ Created ${demoUsers.length} demo users`);

  // Get user and beer IDs for reviews
  const users = await prisma.user.findMany();
  const allBeers = await prisma.beer.findMany();
  const userMap = Object.fromEntries(users.map((u) => [u.username, u.id]));

  // Create sample reviews
  const sampleReviews = [
    // Hophead's reviews
    {
      userId: userMap['hophead'],
      beerSlug: 'russian-river-pliny-the-elder',
      rating: 5.0,
      content: 'The gold standard for Double IPAs. Perfect balance of hop bitterness and malt sweetness. Every beer enthusiast needs to try this at least once. The citrus and pine notes are incredible, and it finishes clean despite the 8% ABV.',
      flavorTags: ['hoppy', 'citrus', 'balanced', 'piney'],
      aroma: 5.0,
      appearance: 4.5,
      taste: 5.0,
      mouthfeel: 4.5,
      overall: 5.0,
      servingType: 'draft',
    },
    {
      userId: userMap['hophead'],
      beerSlug: 'tree-house-julius',
      rating: 4.5,
      content: 'Absolutely phenomenal hazy IPA. The mouthfeel is like velvet and the tropical fruit bomb hits you immediately. Mango, passion fruit, and a hint of peach. So smooth you forget it\'s almost 7%.',
      flavorTags: ['hazy', 'tropical', 'juicy', 'smooth'],
      aroma: 5.0,
      appearance: 4.5,
      taste: 5.0,
      mouthfeel: 5.0,
      overall: 4.5,
      servingType: 'can',
    },
    {
      userId: userMap['hophead'],
      beerSlug: 'alchemist-heady-topper',
      rating: 5.0,
      content: 'The OG hazy IPA. Drink from the can as instructed - it really does make a difference. Incredibly juicy with notes of tropical fruit and pine. A perfect beer that started a revolution.',
      flavorTags: ['hazy', 'tropical', 'piney', 'legendary'],
      aroma: 5.0,
      appearance: 4.0,
      taste: 5.0,
      mouthfeel: 5.0,
      overall: 5.0,
      servingType: 'can',
    },
    {
      userId: userMap['hophead'],
      beerSlug: 'bells-two-hearted-ale',
      rating: 4.5,
      content: 'A timeless classic. Centennial hops shine through with grapefruit and floral notes. Perfectly balanced with just enough malt backbone. This is what American IPA should taste like.',
      flavorTags: ['hoppy', 'grapefruit', 'floral', 'classic'],
      aroma: 4.5,
      appearance: 4.5,
      taste: 4.5,
      mouthfeel: 4.0,
      overall: 4.5,
      servingType: 'can',
    },

    // Stout Steve's reviews
    {
      userId: userMap['stoutlover'],
      beerSlug: 'founders-kbs',
      rating: 5.0,
      content: 'Liquid perfection. The bourbon barrel aging adds incredible depth - vanilla, oak, and subtle heat that complements the coffee and chocolate. One of the best stouts money can buy. Worth every penny.',
      flavorTags: ['bourbon', 'coffee', 'chocolate', 'complex'],
      aroma: 5.0,
      appearance: 5.0,
      taste: 5.0,
      mouthfeel: 5.0,
      overall: 5.0,
      servingType: 'bottle',
    },
    {
      userId: userMap['stoutlover'],
      beerSlug: 'founders-breakfast-stout',
      rating: 4.5,
      content: 'The best breakfast stout on the market at this price point. Coffee forward with rich chocolate notes and a creamy oatmeal body. Could drink this every morning (but probably shouldn\'t).',
      flavorTags: ['coffee', 'chocolate', 'oatmeal', 'creamy'],
      aroma: 4.5,
      appearance: 4.5,
      taste: 4.5,
      mouthfeel: 5.0,
      overall: 4.5,
      servingType: 'bottle',
    },
    {
      userId: userMap['stoutlover'],
      beerSlug: '3-floyds-dark-lord',
      rating: 5.0,
      content: 'The holy grail of imperial stouts. Intense, complex, and utterly unique. Notes of molasses, dark fruit, and baker\'s chocolate. Thick as motor oil. Only available on Dark Lord Day - worth the pilgrimage.',
      flavorTags: ['intense', 'molasses', 'dark fruit', 'chocolate'],
      aroma: 5.0,
      appearance: 5.0,
      taste: 5.0,
      mouthfeel: 4.5,
      overall: 5.0,
      servingType: 'bottle',
    },
    {
      userId: userMap['stoutlover'],
      beerSlug: 'cigar-city-hunahpus',
      rating: 4.5,
      content: 'An incredible marriage of chocolate and spice. The ancho chiles add a subtle heat that builds with each sip. Complex and warming. A fantastic special release stout.',
      flavorTags: ['chocolate', 'spicy', 'cinnamon', 'complex'],
      aroma: 4.5,
      appearance: 5.0,
      taste: 4.5,
      mouthfeel: 4.5,
      overall: 4.5,
      servingType: 'bottle',
    },
    {
      userId: userMap['stoutlover'],
      beerSlug: 'deschutes-black-butte-porter',
      rating: 4.0,
      content: 'The gateway to dark beer. Incredibly smooth with notes of chocolate and coffee without being overwhelming. Perfect for introducing friends to porters.',
      flavorTags: ['chocolate', 'coffee', 'smooth', 'balanced'],
      aroma: 4.0,
      appearance: 4.0,
      taste: 4.0,
      mouthfeel: 4.5,
      overall: 4.0,
      servingType: 'draft',
    },

    // Sour Sarah's reviews
    {
      userId: userMap['sourpusher'],
      beerSlug: 'cantillon-gueuze',
      rating: 5.0,
      content: 'The pinnacle of sour beer. Bone dry, incredibly complex, and perfectly tart. Notes of lemon, green apple, and barnyard funk. This is what beer tasted like hundreds of years ago.',
      flavorTags: ['sour', 'funky', 'complex', 'tart'],
      aroma: 5.0,
      appearance: 4.5,
      taste: 5.0,
      mouthfeel: 4.5,
      overall: 5.0,
      servingType: 'bottle',
    },
    {
      userId: userMap['sourpusher'],
      beerSlug: 'cantillon-rose-de-gambrinus',
      rating: 5.0,
      content: 'Raspberry perfection. Tart, fruity, and incredibly elegant. The raspberries complement the lambic base beautifully without overwhelming it. My desert island beer.',
      flavorTags: ['sour', 'raspberry', 'elegant', 'fruity'],
      aroma: 5.0,
      appearance: 5.0,
      taste: 5.0,
      mouthfeel: 4.5,
      overall: 5.0,
      servingType: 'bottle',
    },
    {
      userId: userMap['sourpusher'],
      beerSlug: 'russian-river-supplication',
      rating: 4.5,
      content: 'American sour at its finest. The cherry and Pinot Noir barrel character combine beautifully with the Brett funk. Complex, tart, and wine-like. Perfect with dinner.',
      flavorTags: ['sour', 'cherry', 'wine', 'complex'],
      aroma: 4.5,
      appearance: 4.5,
      taste: 5.0,
      mouthfeel: 4.0,
      overall: 4.5,
      servingType: 'bottle',
    },
    {
      userId: userMap['sourpusher'],
      beerSlug: 'jester-king-atrial-rubicite',
      rating: 4.5,
      content: 'Texas terroir in a glass. The raspberries shine through with beautiful tartness. Funky, fruity, and absolutely delicious. Jester King continues to impress.',
      flavorTags: ['sour', 'raspberry', 'funky', 'fruity'],
      aroma: 4.5,
      appearance: 5.0,
      taste: 4.5,
      mouthfeel: 4.0,
      overall: 4.5,
      servingType: 'bottle',
    },
    {
      userId: userMap['sourpusher'],
      beerSlug: 'dogfish-head-seaquench',
      rating: 3.5,
      content: 'Great sessionable sour for hot days. The lime and salt are refreshing without being overwhelming. Not as complex as traditional sours, but perfect for the beach.',
      flavorTags: ['sour', 'salty', 'lime', 'refreshing'],
      aroma: 3.5,
      appearance: 3.5,
      taste: 3.5,
      mouthfeel: 4.0,
      overall: 3.5,
      servingType: 'can',
    },

    // Demo user reviews
    {
      userId: userMap['demo'],
      beerSlug: 'sierra-nevada-pale-ale',
      rating: 4.0,
      content: 'The beer that started my craft journey. Still holds up after all these years. Perfect balance of citrus hops and caramel malt. A true American classic.',
      flavorTags: ['hoppy', 'citrus', 'balanced', 'classic'],
      aroma: 4.0,
      appearance: 4.0,
      taste: 4.0,
      mouthfeel: 4.0,
      overall: 4.0,
      servingType: 'bottle',
    },
    {
      userId: userMap['demo'],
      beerSlug: 'weihenstephaner-hefeweissbier',
      rating: 4.5,
      content: 'The world\'s oldest brewery still makes some of the world\'s best beer. Classic banana and clove character with a fluffy wheat body. Perfect with brunch.',
      flavorTags: ['wheat', 'banana', 'clove', 'refreshing'],
      aroma: 4.5,
      appearance: 4.5,
      taste: 4.5,
      mouthfeel: 4.5,
      overall: 4.5,
      servingType: 'draft',
    },
    {
      userId: userMap['demo'],
      beerSlug: 'founders-all-day-ipa',
      rating: 3.5,
      content: 'My go-to session IPA. Low ABV but still packed with hop flavor. Perfect for day drinking without getting too fuzzy. Lives up to its name.',
      flavorTags: ['hoppy', 'sessionable', 'citrus', 'light'],
      aroma: 3.5,
      appearance: 3.5,
      taste: 3.5,
      mouthfeel: 3.5,
      overall: 3.5,
      servingType: 'can',
    },

    // Craft Curious reviews
    {
      userId: userMap['craftcurious'],
      beerSlug: 'bells-oberon',
      rating: 4.0,
      content: 'My first wheat beer and I\'m hooked! Light, refreshing, and slightly fruity. Perfect summer beer. Excited to explore more of this style.',
      flavorTags: ['wheat', 'citrus', 'refreshing', 'light'],
      aroma: 4.0,
      appearance: 4.0,
      taste: 4.0,
      mouthfeel: 4.0,
      overall: 4.0,
      servingType: 'draft',
    },
    {
      userId: userMap['craftcurious'],
      beerSlug: 'sierra-nevada-hazy-little-thing',
      rating: 4.0,
      content: 'This was my intro to hazy IPAs and I loved it! So juicy and smooth. Way less bitter than I expected from an IPA. Definitely ordering again.',
      flavorTags: ['hazy', 'juicy', 'tropical', 'smooth'],
      aroma: 4.0,
      appearance: 4.0,
      taste: 4.0,
      mouthfeel: 4.0,
      overall: 4.0,
      servingType: 'can',
    },
    {
      userId: userMap['craftcurious'],
      beerSlug: 'dogfish-head-60-minute-ipa',
      rating: 3.5,
      content: 'Trying to understand IPAs better. This one is nicely balanced - not too bitter for a newbie like me. I can taste the citrus everyone talks about!',
      flavorTags: ['hoppy', 'citrus', 'balanced', 'smooth'],
      aroma: 3.5,
      appearance: 4.0,
      taste: 3.5,
      mouthfeel: 4.0,
      overall: 3.5,
      servingType: 'bottle',
    },
  ];

  for (const review of sampleReviews) {
    const beer = allBeers.find((b) => b.slug === review.beerSlug);
    if (!beer) continue;

    await prisma.review.upsert({
      where: { userId_beerId: { userId: review.userId, beerId: beer.id } },
      create: {
        userId: review.userId,
        beerId: beer.id,
        rating: review.rating,
        content: review.content,
        flavorTags: review.flavorTags,
        aroma: review.aroma,
        appearance: review.appearance,
        taste: review.taste,
        mouthfeel: review.mouthfeel,
        overall: review.overall,
        servingType: review.servingType,
        isVerified: true,
      },
      update: {},
    });
  }

  console.log(`✅ Created ${sampleReviews.length} reviews`);

  console.log('\n🌱 Database seeding complete!');
  console.log('\n📝 Demo accounts:');
  console.log('   demo@brewiq.ai / Demo123!');
  console.log('   hophead@brewiq.ai / Demo123!');
  console.log('   stoutlover@brewiq.ai / Demo123!');
  console.log('   sourpusher@brewiq.ai / Demo123!');
  console.log('   craftcurious@brewiq.ai / Demo123!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
